"""Internal operator CLI package (Phase 8B split from cli.py)."""

from origenlab_email_pipeline.operator_cli.constants import (
    CLI_COMMAND_NAMES,
    GMAIL_INGEST_COMMANDS,
    GMAIL_INGEST_INBOX_FOLDER,
    GMAIL_INGEST_SCRIPT,
    GMAIL_INGEST_SENT_FOLDER,
    HELP_ONLY_SUBCOMMANDS,
    MIRROR_DASHBOARD_COMMAND,
    MIRROR_DASHBOARD_SYNC_SCRIPT,
    POSTGRES_ENV_VARS,
    REFRESH_DASHBOARD_COMMAND,
    REFRESH_DASHBOARD_USAGE,
    SPECIAL_COMMANDS,
    SUBCOMMAND_HELP,
    SUBCOMMAND_SCRIPTS,
)
from origenlab_email_pipeline.operator_cli.gmail import (
    build_gmail_ingest_argv_list,
    build_gmail_ingest_folders_argv,
    run_gmail_ingest,
    validate_gmail_ingest_passthrough,
)
from origenlab_email_pipeline.operator_cli.mirror import (
    build_mirror_dashboard_alembic_argv,
    build_mirror_dashboard_argv_list,
    build_mirror_dashboard_sync_argv,
    mirror_dashboard_sync_safety_flags,
    mirror_dashboard_uses_cloud_postgres_only,
    missing_postgres_env_message,
    parse_mirror_dashboard_wrapper_args,
    postgres_url_configured,
    run_mirror_dashboard,
)
from origenlab_email_pipeline.operator_cli.parser import main
from origenlab_email_pipeline.operator_cli.paths import (
    gmail_ingest_script_path,
    mirror_dashboard_sync_script_path,
    normalize_passthrough_args,
    repo_root,
    script_path_for,
)
from origenlab_email_pipeline.operator_cli.refresh import (
    RefreshDashboardOptions,
    RefreshDashboardStep,
    SubcommandRunner,
    build_refresh_dashboard_steps,
    parse_refresh_dashboard_wrapper_args,
    run_refresh_dashboard,
)
from origenlab_email_pipeline.operator_cli.runner import build_subcommand_argv, run_subcommand

__all__ = [
    "CLI_COMMAND_NAMES",
    "GMAIL_INGEST_COMMANDS",
    "GMAIL_INGEST_INBOX_FOLDER",
    "GMAIL_INGEST_SCRIPT",
    "GMAIL_INGEST_SENT_FOLDER",
    "HELP_ONLY_SUBCOMMANDS",
    "MIRROR_DASHBOARD_COMMAND",
    "MIRROR_DASHBOARD_SYNC_SCRIPT",
    "POSTGRES_ENV_VARS",
    "REFRESH_DASHBOARD_COMMAND",
    "REFRESH_DASHBOARD_USAGE",
    "RefreshDashboardOptions",
    "RefreshDashboardStep",
    "SPECIAL_COMMANDS",
    "SUBCOMMAND_HELP",
    "SUBCOMMAND_SCRIPTS",
    "SubcommandRunner",
    "build_gmail_ingest_argv_list",
    "build_gmail_ingest_folders_argv",
    "build_mirror_dashboard_alembic_argv",
    "build_mirror_dashboard_argv_list",
    "build_mirror_dashboard_sync_argv",
    "build_refresh_dashboard_steps",
    "build_subcommand_argv",
    "gmail_ingest_script_path",
    "main",
    "mirror_dashboard_sync_safety_flags",
    "mirror_dashboard_sync_script_path",
    "mirror_dashboard_uses_cloud_postgres_only",
    "missing_postgres_env_message",
    "normalize_passthrough_args",
    "parse_mirror_dashboard_wrapper_args",
    "parse_refresh_dashboard_wrapper_args",
    "postgres_url_configured",
    "repo_root",
    "run_gmail_ingest",
    "run_mirror_dashboard",
    "run_refresh_dashboard",
    "run_subcommand",
    "script_path_for",
    "validate_gmail_ingest_passthrough",
]
