"""Product images: the Storage client, the upload and update commands, signed URLs.

Local Supabase has Storage disabled (a hosted gate), so nothing here reaches a real bucket: the
routes and commands run against `FakeStorage`, and `SupabaseStorage` is exercised against an
httpx `MockTransport` that checks the exact requests it would send. Every image is a few
generated bytes; every name and key is invented.
"""
from __future__ import annotations

import hashlib
import json
import struct
import threading
import time
import uuid
import zlib

import httpx
import psycopg
import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from pydantic import SecretStr

from origenlab_api.commercial_operator_identity import OPERATOR_EMAIL_HEADER
from origenlab_api.errors import register_exception_handlers
from origenlab_api.v2.catalog.storage import (
    MAX_IMAGE_BYTES,
    SIGNED_URL_SECONDS,
    FakeStorage,
    ImageRefused,
    StorageUnavailable,
    SupabaseStorage,
    check_image,
    image_path,
)
from origenlab_api.v2.commands import CommandRefused, request_digest
from origenlab_api.v2.identity import LocalDevIdentity, OperatorIdentity, OperatorLookup
from v2_command_harness import build_disposable_database, needs_db, runtime_dsn

LOOPBACK = "postgresql://origenlab_api:pw@127.0.0.1:54332/origenlab_dev"
HEADERS = {OPERATOR_EMAIL_HEADER: "op@example.test"}
PID = "00000000-0000-4000-8000-0000000000aa"
IMG = "00000000-0000-4000-8000-0000000000cc"
BASE = "https://example-ref.supabase.invalid"
KEY = "sb_secret_" + "x" * 32  # invented; the shape of the dedicated Storage key, nothing more


# ──────────────────────────────────────────────────────────── synthetic images ──

def _png(seed: int = 0) -> bytes:
    """A real 1×1 PNG whose single pixel colour is the seed, so seeds give different hashes."""
    def chunk(kind: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))
    pixel = bytes([0, seed % 256, (seed // 256) % 256, 7])
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(pixel)) + chunk(b"IEND", b""))


def _jpeg(seed: int = 0) -> bytes:
    return b"\xff\xd8\xff\xe0\x00\x10JFIF\x00" + bytes([seed % 256]) * 32 + b"\xff\xd9"


def _webp(seed: int = 0) -> bytes:
    body = b"WEBPVP8L" + struct.pack("<I", 8) + bytes([seed % 256]) * 8
    return b"RIFF" + struct.pack("<I", len(body)) + body


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# ──────────────────────────────────────────────────────────── pure rules ──

def test_image_path_is_content_addressed_per_product() -> None:
    sha = "a" * 64
    assert image_path(uuid.UUID(PID), sha, "image/jpeg") == f"products/{PID}/{sha}.jpg"
    assert image_path(uuid.UUID(PID), sha, "image/png") == f"products/{PID}/{sha}.png"
    assert image_path(uuid.UUID(PID), sha, "image/webp") == f"products/{PID}/{sha}.webp"
    with pytest.raises(ValueError):
        image_path(uuid.UUID(PID), sha, "image/gif")
    with pytest.raises(ValueError):
        image_path(uuid.UUID(PID), "not-a-hash", "image/png")


@pytest.mark.parametrize(("data", "declared"), [
    (_png(), "image/png"), (_jpeg(), "image/jpeg"), (_webp(), "image/webp"),
    (_png(), "IMAGE/PNG; charset=binary"),
])
def test_check_image_accepts_a_declared_type_its_bytes_agree_with(data, declared) -> None:
    assert check_image(data, declared) == declared.split(";")[0].strip().lower()


@pytest.mark.parametrize(("data", "declared"), [
    (_png(), "image/jpeg"),            # PNG declared as JPEG
    (_jpeg(), "image/png"),
    (_webp(), "image/png"),
    (b"GIF89a" + b"\x00" * 20, "image/gif"),
    (b"<svg xmlns='http://www.w3.org/2000/svg'/>", "image/svg+xml"),
    (b"<svg/>", "image/png"),          # wrong bytes behind an allowed type
    (b"", "image/png"),
    (_png(), None),
    (b"RIFF\x00\x00\x00\x00WAVEfmt ", "image/webp"),
])
def test_check_image_refuses_anything_else_as_415(data, declared) -> None:
    with pytest.raises(ImageRefused) as exc:
        check_image(data, declared)
    assert (exc.value.status_code, exc.value.code) == (415, "unsupported_image")


def test_check_image_refuses_more_than_eight_mebibytes_as_413() -> None:
    assert MAX_IMAGE_BYTES == 8_388_608
    big = _png() + b"\x00" * (MAX_IMAGE_BYTES - len(_png()) + 1)
    with pytest.raises(ImageRefused) as exc:
        check_image(big, "image/png")
    assert (exc.value.status_code, exc.value.code) == (413, "image_too_large")
    exact = _png() + b"\x00" * (MAX_IMAGE_BYTES - len(_png()))
    assert check_image(exact, "image/png") == "image/png"


def test_signed_urls_live_ten_minutes_at_most() -> None:
    assert SIGNED_URL_SECONDS == 600
    storage = FakeStorage()
    for bad in (0, -1, 601, 3600):
        with pytest.raises(ValueError):
            storage.signed_url("products/x/y.png", bad)


def test_fake_storage_puts_once_and_signs() -> None:
    storage = FakeStorage()
    storage.put_if_absent("products/p/a.png", b"one", "image/png")
    storage.put_if_absent("products/p/a.png", b"two", "image/png")  # already present: kept
    assert storage.objects == {"products/p/a.png": (b"one", "image/png")}
    assert storage.puts == 2
    url = storage.signed_url("products/p/a.png", 600)
    assert "products/p/a.png" in url and "600" in url


# ──────────────────────────────────────────────────────── SupabaseStorage over HTTP ──

def _supabase(handler) -> tuple[SupabaseStorage, list[httpx.Request]]:
    seen: list[httpx.Request] = []

    def record(request: httpx.Request) -> httpx.Response:
        seen.append(request)
        return handler(request)

    return SupabaseStorage(BASE, KEY, httpx.Client(transport=httpx.MockTransport(record))), seen


def test_put_if_absent_posts_the_bytes_without_upsert() -> None:
    storage, seen = _supabase(lambda r: httpx.Response(200, json={"Key": "catalog/products/p/a.png"}))
    storage.put_if_absent(f"products/{PID}/{'b' * 64}.png", _png(), "image/png")
    [request] = seen
    assert request.method == "POST"
    assert str(request.url) == f"{BASE}/storage/v1/object/catalog/products/{PID}/{'b' * 64}.png"
    assert request.headers["authorization"] == f"Bearer {KEY}"
    assert request.headers["apikey"] == KEY
    assert request.headers["x-upsert"] == "false"
    assert request.headers["content-type"] == "image/png"
    assert request.content == _png()


@pytest.mark.parametrize("response", [
    httpx.Response(409, json={"statusCode": "409", "error": "Duplicate", "message": "The resource already exists"}),
    # Older Storage API versions answer a duplicate as HTTP 400 with the 409 in the body.
    httpx.Response(400, json={"statusCode": "409", "error": "Duplicate", "message": "The resource already exists"}),
])
def test_an_object_already_there_is_success(response) -> None:
    storage, seen = _supabase(lambda r: response)
    storage.put_if_absent("products/p/a.png", _png(), "image/png")
    assert len(seen) == 1


@pytest.mark.parametrize("response", [
    httpx.Response(400, json={"statusCode": "400", "error": "InvalidKey", "message": "bad key"}),
    httpx.Response(403, json={"statusCode": "403", "error": "Unauthorized"}),
    httpx.Response(500, text="boom"),
    httpx.Response(400, text="not json"),
])
def test_any_other_answer_is_storage_unavailable_without_the_key(response) -> None:
    storage, _ = _supabase(lambda r: response)
    with pytest.raises(StorageUnavailable) as exc:
        storage.put_if_absent("products/p/a.png", _png(), "image/png")
    assert KEY not in str(exc.value) and KEY not in repr(exc.value)


def test_a_transport_failure_is_storage_unavailable() -> None:
    def fail(request):
        raise httpx.ConnectTimeout("timed out", request=request)

    storage, _ = _supabase(fail)
    with pytest.raises(StorageUnavailable):
        storage.put_if_absent("products/p/a.png", _png(), "image/png")
    with pytest.raises(StorageUnavailable):
        storage.signed_url("products/p/a.png", 600)


def test_signed_url_asks_storage_to_sign_and_returns_an_absolute_url() -> None:
    signed = f"/object/sign/catalog/products/{PID}/a.png?token=invented.jwt.value"
    storage, seen = _supabase(lambda r: httpx.Response(200, json={"signedURL": signed}))
    url = storage.signed_url(f"products/{PID}/a.png", 600)
    assert url == f"{BASE}/storage/v1{signed}"
    [request] = seen
    assert request.method == "POST"
    assert str(request.url) == f"{BASE}/storage/v1/object/sign/catalog/products/{PID}/a.png"
    assert request.headers["authorization"] == f"Bearer {KEY}" and request.headers["apikey"] == KEY
    assert request.headers["content-type"] == "application/json"
    assert json.loads(request.content) == {"expiresIn": 600}


@pytest.mark.parametrize("response", [
    httpx.Response(404, json={"statusCode": "404", "error": "not_found"}),
    httpx.Response(200, json={"nope": 1}),
    httpx.Response(200, json={"signedURL": "https://elsewhere.invalid/x"}),
    httpx.Response(200, text="not json"),
])
def test_a_signing_failure_is_storage_unavailable(response) -> None:
    storage, _ = _supabase(lambda r: response)
    with pytest.raises(StorageUnavailable):
        storage.signed_url("products/p/a.png", 600)


def test_supabase_storage_refuses_a_long_lived_url_before_asking() -> None:
    storage, seen = _supabase(lambda r: httpx.Response(200, json={"signedURL": "/object/sign/x"}))
    with pytest.raises(ValueError):
        storage.signed_url("products/p/a.png", 601)
    assert seen == []


@pytest.mark.parametrize(("base", "key"), [
    ("http://example-ref.supabase.invalid", KEY),    # the key would cross the network in clear
    ("ftp://example-ref.supabase.invalid", KEY),
    ("https://user:pw@example-ref.supabase.invalid", KEY),
    (BASE, "eyJhbGciOiJIUzI1NiJ9.legacy.service_role"),  # legacy JWT keys are not used (§7)
    (BASE, ""),
])
def test_supabase_storage_refuses_an_unsafe_configuration(base, key) -> None:
    with pytest.raises(ValueError) as exc:
        SupabaseStorage(base, key, httpx.Client())
    assert key not in str(exc.value) or not key


def test_supabase_storage_allows_plain_http_only_to_a_loopback_literal() -> None:
    SupabaseStorage("http://127.0.0.1:54321", KEY, httpx.Client())
    SupabaseStorage(BASE + "/", KEY, httpx.Client())  # a trailing slash is not doubled


def test_supabase_storage_never_shows_its_key() -> None:
    storage, _ = _supabase(lambda r: httpx.Response(200))
    assert KEY not in repr(storage) and KEY not in str(storage)


# ──────────────────────────────────────────────────────── settings and mounting ──

def test_storage_settings_come_from_the_environment_as_a_secret(monkeypatch) -> None:
    from origenlab_api.settings import Settings

    monkeypatch.setenv("ORIGENLAB_V2_STORAGE_URL", BASE)
    monkeypatch.setenv("ORIGENLAB_V2_STORAGE_SECRET_KEY", KEY)
    settings = Settings(_env_file=None)
    assert settings.v2_storage_url == BASE
    assert isinstance(settings.v2_storage_secret_key, SecretStr)
    assert settings.v2_storage_secret_key.get_secret_value() == KEY
    assert KEY not in repr(settings) and KEY not in str(settings.model_dump())
    assert settings.catalog_storage_configured() is True
    monkeypatch.delenv("ORIGENLAB_V2_STORAGE_SECRET_KEY")
    assert Settings(_env_file=None).catalog_storage_configured() is False


def test_mount_builds_storage_only_when_configured(caplog) -> None:
    from origenlab_api import main
    from origenlab_api.settings import Settings

    on = {"v2_database_url": LOOPBACK, "v2_quoting_enabled": True}
    app = FastAPI()
    main._mount_catalog(app, Settings(_env_file=None, **on), LOOPBACK, lambda *a, **k: 1 / 0)
    assert app.state.catalog_storage is None
    app = FastAPI()
    main._mount_catalog(app, Settings(_env_file=None, **on, v2_storage_url=BASE, v2_storage_secret_key=KEY),
                        LOOPBACK, lambda *a, **k: 1 / 0)
    assert isinstance(app.state.catalog_storage, SupabaseStorage)
    paths = set(app.openapi()["paths"])
    assert {"/v2/commands/add-product-image", "/v2/commands/update-product-image",
            "/v2/catalog/images/{image_id}/url"} <= paths
    # A configuration that would leak the key is refused: images answer 503, the API still starts.
    app = FastAPI()
    with caplog.at_level("WARNING"):
        main._mount_catalog(app, Settings(_env_file=None, **on, v2_storage_url="http://example.invalid",
                                          v2_storage_secret_key=KEY), LOOPBACK, lambda *a, **k: 1 / 0)
    assert app.state.catalog_storage is None
    assert KEY not in caplog.text


# ──────────────────────────────────────────────────────── routes (no database) ──

class _Lookup(OperatorLookup):
    def __init__(self, operator):
        self._operator = operator

    def by_email(self, email_norm):
        return self._operator


class _FakeRepo:
    """Records each command and what Storage held at that moment."""

    def __init__(self, storage, refusal: CommandRefused | None = None):
        self.calls: list[dict] = []
        self.stored_at_call: list[set] = []
        self._storage = storage
        self._refusal = refusal

    def execute(self, **kwargs):
        self.calls.append(kwargs)
        self.stored_at_call.append(set(getattr(self._storage, "objects", {})))
        if self._refusal is not None:
            raise self._refusal
        return {"ok": True, "replayed": False}


class _FakeReads:
    def __init__(self, images: dict[str, dict]):
        self._images = images

    def image(self, image_id):
        return self._images.get(str(image_id))

    def product_exists(self, product_id):
        return str(product_id) == PID


def _operator(role: str) -> OperatorIdentity:
    return OperatorIdentity(operator_id="00000000-0000-4000-8000-000000000001", email_norm="op@example.test",
                            display_name="Op", role=role, status="active")


def _client(role="sales", *, storage="fake", refusal=None, images=None):
    from origenlab_api.v2.catalog.routes import catalog_command_router, catalog_read_router

    app = FastAPI()
    register_exception_handlers(app)  # the envelope production serves, not FastAPI's default
    app.include_router(catalog_read_router)
    app.include_router(catalog_command_router)
    app.state.catalog_storage = FakeStorage() if storage == "fake" else storage
    app.state.catalog_repository = _FakeRepo(app.state.catalog_storage, refusal)
    app.state.catalog_reads = _FakeReads(images or {})
    app.state.v2_identity = LocalDevIdentity(LOOPBACK, _Lookup(_operator(role)))
    return app, TestClient(app)


def _ikey():
    return {**HEADERS, "Idempotency-Key": uuid.uuid4().hex}


def _upload(client, data: bytes, content_type: str = "image/png", *, headers=None, **form):
    return client.post("/v2/commands/add-product-image", headers=headers or _ikey(),
                       data={"product_id": PID, **form}, files={"file": ("foto.bin", data, content_type)})


def test_upload_stores_the_object_first_then_runs_the_command_over_its_hash() -> None:
    app, client = _client()
    data = _png(1)
    r = _upload(client, data, caption_es="Vista frontal", source="manufacturer_site",
                source_url="https://fabricante.example/sonicador")
    assert r.status_code == 200, r.text
    path = f"products/{PID}/{_sha(data)}.png"
    assert app.state.catalog_storage.objects == {path: (data, "image/png")}
    [call] = app.state.catalog_repository.calls
    assert app.state.catalog_repository.stored_at_call == [{path}]  # Storage before the transaction
    assert call["command_name"] == "add-product-image" and call["operator"].role == "sales"
    assert call["fields"] == {"product_id": PID, "sha256": _sha(data), "content_type": "image/png",
                              "storage_path": path, "caption_es": "Vista frontal", "source": "manufacturer_site",
                              "source_url": "https://fabricante.example/sonicador"}
    json.dumps(call["fields"])
    # The digest covers the hash and the form, never the bytes.
    from origenlab_api.v2.catalog.routes import AddProductImageFields

    assert call["digest"] == request_digest("add-product-image", AddProductImageFields(**call["fields"]))


def test_same_bytes_same_form_same_digest_and_different_bytes_differ() -> None:
    app, client = _client()
    _upload(client, _png(1))
    _upload(client, _png(1))
    _upload(client, _png(2))
    digests = [c["digest"] for c in app.state.catalog_repository.calls]
    assert digests[0] == digests[1] != digests[2]


def test_blank_optional_form_fields_are_absent_and_source_defaults_to_upload() -> None:
    app, client = _client()
    r = _upload(client, _jpeg(), "image/jpeg", caption_es="", source_url="")
    assert r.status_code == 200, r.text
    fields = app.state.catalog_repository.calls[0]["fields"]
    assert (fields["caption_es"], fields["source_url"], fields["source"]) == (None, None, "upload")
    assert fields["storage_path"].endswith(".jpg")


def test_oversize_upload_is_413_and_stores_nothing() -> None:
    app, client = _client()
    r = _upload(client, _png() + b"\x00" * MAX_IMAGE_BYTES)
    assert r.status_code == 413
    err = r.json()["error"]
    assert err["details"]["code"] == "image_too_large"
    assert app.state.catalog_storage.objects == {} and app.state.catalog_repository.calls == []


def test_a_body_declared_far_over_the_limit_is_413_before_it_is_read() -> None:
    app, client = _client()
    r = client.post("/v2/commands/add-product-image", headers={**_ikey(), "content-type": "multipart/form-data; "
                    "boundary=x"}, content=b"x" * (MAX_IMAGE_BYTES + 128 * 1024))
    assert r.status_code == 413 and r.json()["error"]["details"]["code"] == "image_too_large"
    assert app.state.catalog_storage.objects == {}


def test_a_body_without_a_length_is_capped_while_it_streams() -> None:
    import asyncio

    from fastapi import HTTPException
    from starlette.requests import Request

    from origenlab_api.v2.catalog.routes import _read_capped_body

    chunks = [b"x" * 1024] * 8

    async def receive():
        body = chunks.pop() if chunks else b""
        return {"type": "http.request", "body": body, "more_body": bool(chunks)}

    request = Request({"type": "http", "method": "POST", "headers": []}, receive)
    with pytest.raises(HTTPException) as exc:
        asyncio.run(_read_capped_body(request, 4096))
    assert exc.value.status_code == 413


@pytest.mark.parametrize(("data", "declared"), [
    (_png(), "image/jpeg"), (b"GIF89a....", "image/gif"), (b"<svg/>", "image/svg+xml"), (b"", "image/png")])
def test_wrong_or_unsupported_type_is_415_and_stores_nothing(data, declared) -> None:
    app, client = _client()
    r = _upload(client, data, declared)
    assert r.status_code == 415
    assert r.json()["error"]["details"]["code"] == "unsupported_image"
    assert app.state.catalog_storage.objects == {} and app.state.catalog_repository.calls == []


def test_storage_not_configured_is_503() -> None:
    app, client = _client(storage=None)
    r = _upload(client, _png())
    assert r.status_code == 503
    assert r.json()["error"]["details"]["code"] == "storage_unavailable"
    assert app.state.catalog_repository.calls == []


def test_storage_failing_is_503_and_the_command_never_runs() -> None:
    class _Down(FakeStorage):
        def put_if_absent(self, path, data, content_type):
            raise StorageUnavailable("storage answered HTTP 500")

    app, client = _client(storage=_Down())
    r = _upload(client, _png())
    assert r.status_code == 503 and r.json()["error"]["details"]["code"] == "storage_unavailable"
    assert app.state.catalog_repository.calls == []


def test_viewer_may_not_upload_and_nothing_is_stored() -> None:
    app, client = _client("viewer")
    r = _upload(client, _png())
    assert r.status_code == 403 and r.json()["error"]["details"]["code"] == "role_may_not_decide"
    assert app.state.catalog_storage.objects == {}


def test_unauthenticated_upload_is_401() -> None:
    app, client = _client()
    r = client.post("/v2/commands/add-product-image", data={"product_id": PID},
                    files={"file": ("a.png", _png(), "image/png")})
    assert r.status_code == 401 and app.state.catalog_storage.objects == {}


def test_upload_without_idempotency_key_is_400_and_stores_nothing() -> None:
    app, client = _client()
    r = _upload(client, _png(), headers=HEADERS)
    assert r.status_code == 400 and r.json()["error"]["details"]["code"] == "idempotency_key_required"
    assert app.state.catalog_storage.objects == {}


@pytest.mark.parametrize("form", [
    {"product_id": "not-a-uuid"},
    {"source": "scraped"},
    {"source_url": "javascript:alert(1)"},
    {"caption_es": "x" * 501},
    {"surprise": "1"},
])
def test_bad_upload_forms_are_422_in_the_production_envelope(form) -> None:
    app, client = _client()
    r = _upload(client, _png(), **form)
    assert r.status_code == 422, r.text
    assert r.json()["error"]["code"] == "validation_error"
    assert app.state.catalog_storage.objects == {} and app.state.catalog_repository.calls == []


def test_upload_without_a_file_or_with_two_is_refused() -> None:
    app, client = _client()
    r = client.post("/v2/commands/add-product-image", headers=_ikey(), data={"product_id": PID},
                    files={"other": ("a.txt", b"hola", "text/plain")})
    assert r.status_code == 422
    r = client.post("/v2/commands/add-product-image", headers=_ikey(), data={"product_id": PID},
                    files=[("file", ("a.png", _png(1), "image/png")), ("file", ("b.png", _png(2), "image/png"))])
    assert r.status_code in (400, 422)
    assert app.state.catalog_storage.objects == {} and app.state.catalog_repository.calls == []


def test_an_unknown_product_is_404_before_anything_is_stored() -> None:
    app, client = _client()
    r = client.post("/v2/commands/add-product-image", headers=_ikey(), data={"product_id": str(uuid.uuid4())},
                    files={"file": ("a.png", _png(), "image/png")})
    assert r.status_code == 404 and r.json()["error"]["details"]["code"] == "product_not_found"
    assert app.state.catalog_storage.objects == {} and app.state.catalog_repository.calls == []


def test_image_sources_match_the_closed_vocabulary() -> None:
    from typing import get_args

    from origenlab_api.v2.catalog.keys import IMAGE_SOURCES
    from origenlab_api.v2.catalog.routes import ImageSource

    assert get_args(ImageSource) == IMAGE_SOURCES


def test_command_refusals_surface_in_the_production_envelope() -> None:
    _, client = _client(refusal=CommandRefused(404, "product_not_found", "no such product"))
    r = _upload(client, _png())
    assert r.status_code == 404 and r.json()["error"]["details"]["code"] == "product_not_found"


UPDATE = {"image_id": IMG, "expected_version": 1, "status": "hidden"}


@pytest.mark.parametrize("role", ["sales", "admin"])
def test_update_product_image_reaches_the_handler(role) -> None:
    app, client = _client(role)
    r = client.post("/v2/commands/update-product-image", json={**UPDATE, "caption_es": "Lateral", "sort_order": 2},
                    headers=_ikey())
    assert r.status_code == 200, r.text
    [call] = app.state.catalog_repository.calls
    assert call["command_name"] == "update-product-image"
    assert call["fields"]["image_id"] == IMG and call["fields"]["sort_order"] == 2


def test_viewer_may_not_update_an_image() -> None:
    app, client = _client("viewer")
    r = client.post("/v2/commands/update-product-image", json=UPDATE, headers=_ikey())
    assert r.status_code == 403 and app.state.catalog_repository.calls == []


@pytest.mark.parametrize("patch", [
    {"status": "deleted"}, {"status": "proposed"}, {"sort_order": -1}, {"caption_es": "x" * 501},
    {"surprise": 1}, {"expected_version": None},
])
def test_bad_update_bodies_are_422(patch) -> None:
    app, client = _client()
    r = client.post("/v2/commands/update-product-image", json={**UPDATE, **patch}, headers=_ikey())
    assert r.status_code == 422 and app.state.catalog_repository.calls == []


IMAGES = {
    IMG: {"id": IMG, "product_id": PID, "storage_path": f"products/{PID}/{'c' * 64}.png", "status": "confirmed"},
    "00000000-0000-4000-8000-0000000000dd": {"id": "00000000-0000-4000-8000-0000000000dd", "product_id": PID,
                                             "storage_path": f"products/{PID}/{'d' * 64}.png", "status": "hidden"},
}
HIDDEN = "00000000-0000-4000-8000-0000000000dd"


@pytest.mark.parametrize("role", ["viewer", "sales", "admin"])
def test_signed_url_for_a_confirmed_image(role) -> None:
    _, client = _client(role, images=IMAGES)
    r = client.get(f"/v2/catalog/images/{IMG}/url", headers=HEADERS)
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["expires_in"] == 600 and set(body) == {"url", "expires_in"}
    assert IMAGES[IMG]["storage_path"] in body["url"] and "600" in body["url"]
    assert "no-store" in r.headers["cache-control"]


def test_hidden_image_is_404_for_a_viewer_and_signed_for_sales_and_admin() -> None:
    _, viewer = _client("viewer", images=IMAGES)
    r = viewer.get(f"/v2/catalog/images/{HIDDEN}/url", headers=HEADERS)
    assert r.status_code == 404 and r.json()["error"]["details"]["code"] == "image_not_found"
    for role in ("sales", "admin"):
        _, client = _client(role, images=IMAGES)
        assert client.get(f"/v2/catalog/images/{HIDDEN}/url", headers=HEADERS).status_code == 200


def test_unknown_image_is_404_and_bad_id_is_422() -> None:
    _, client = _client(images=IMAGES)
    r = client.get(f"/v2/catalog/images/{uuid.uuid4()}/url", headers=HEADERS)
    assert r.status_code == 404 and r.json()["error"]["details"]["code"] == "image_not_found"
    assert client.get("/v2/catalog/images/nope/url", headers=HEADERS).status_code == 422


def test_signed_url_without_storage_is_503_and_unauthenticated_is_401() -> None:
    _, client = _client(storage=None, images=IMAGES)
    r = client.get(f"/v2/catalog/images/{IMG}/url", headers=HEADERS)
    assert r.status_code == 503 and r.json()["error"]["details"]["code"] == "storage_unavailable"
    _, client = _client(images=IMAGES)
    assert client.get(f"/v2/catalog/images/{IMG}/url").status_code == 401


def test_signing_failure_is_503() -> None:
    class _Down(FakeStorage):
        def signed_url(self, path, expires_s):
            raise StorageUnavailable("storage answered HTTP 500")

    _, client = _client(storage=_Down(), images=IMAGES)
    r = client.get(f"/v2/catalog/images/{IMG}/url", headers=HEADERS)
    assert r.status_code == 503 and r.json()["error"]["details"]["code"] == "storage_unavailable"


# ──────────────────────────────────────────────────────── against PostgreSQL ──

@pytest.fixture(scope="module")
def disposable_database():
    yield from build_disposable_database()


def _owner(dsn: str, sql: str, params: tuple = ()):
    with psycopg.connect(dsn, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("set role origenlab_owner")
        cur.execute(sql, params)
        return cur.fetchall() if cur.description else None


@pytest.fixture(scope="module")
def db_operator(disposable_database) -> OperatorIdentity:
    email = f"sales-{uuid.uuid4().hex[:8]}@example.test"
    op_id = _owner(
        disposable_database,
        "insert into platform.operator (auth_user_id, email_norm, display_name, role, status) "
        "values (gen_random_uuid(), %s, 'Vendedora Prueba', 'sales', 'active') returning id::text",
        (email,),
    )[0][0]
    return OperatorIdentity(operator_id=op_id, email_norm=email, display_name="Vendedora Prueba",
                            role="sales", status="active")


def _product(dsn: str) -> str:
    maker = _owner(dsn, "insert into crm.organization (kind, name, confirmation) values ('manufacturer', %s, "
                        "'machine_proposed') returning id::text", (f"Fabricante Ficticio {uuid.uuid4().hex[:6]}",))[0][0]
    return _owner(dsn, "insert into catalog.product (manufacturer_organization_id, model_number) values (%s, %s) "
                       "returning id::text", (maker, f"IMG-{uuid.uuid4().hex[:6]}"))[0][0]


def _repo(dsn: str):
    from origenlab_api.v2.catalog.commands import V2CatalogRepository

    return V2CatalogRepository(psycopg.connect, runtime_dsn(dsn))


def _add(dsn: str, operator: OperatorIdentity, product_id: str, data: bytes, content_type: str = "image/png",
         key: str | None = None, **extra) -> dict:
    from origenlab_api.v2.catalog.routes import AddProductImageFields

    sha = _sha(data)
    body = AddProductImageFields(product_id=product_id, sha256=sha, content_type=content_type,
                                 storage_path=image_path(uuid.UUID(product_id), sha, content_type), **extra)
    return _repo(dsn).execute(command_name="add-product-image", operator=operator,
                              fields=body.model_dump(mode="json"), idempotency_key=key or uuid.uuid4().hex,
                              digest=request_digest("add-product-image", body))


def _update(dsn: str, operator: OperatorIdentity, raw: dict) -> dict:
    from origenlab_api.v2.catalog.routes import UpdateProductImageBody

    body = UpdateProductImageBody(**raw)
    return _repo(dsn).execute(command_name="update-product-image", operator=operator,
                              fields=body.model_dump(mode="json"), idempotency_key=uuid.uuid4().hex,
                              digest=request_digest("update-product-image", body))


def _images(dsn: str, product_id: str) -> list[dict]:
    with psycopg.connect(dsn, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("set role origenlab_owner")
        cur.execute("select * from catalog.product_image where product_id = %s order by sort_order, created_at",
                    (product_id,))
        cols = [d[0] for d in cur.description]
        return [dict(zip(cols, r, strict=True)) for r in cur.fetchall()]


def _events(dsn: str, product_id: str) -> list[tuple]:
    return _owner(dsn, "select seq, event_type, payload, actor_kind, actor_operator_id::text from crm.domain_event "
                       "where aggregate_kind = 'product' and aggregate_id = %s order by seq", (product_id,))


@needs_db
def test_add_product_image_records_a_confirmed_row_and_one_event(disposable_database, db_operator) -> None:
    dsn = disposable_database
    pid = _product(dsn)
    data = _png(10)
    out = _add(dsn, db_operator, pid, data, caption_es="Vista frontal", source="upload")
    assert out["ok"] is True and out["already_present"] is False and out["version"] == 1
    [row] = _images(dsn, pid)
    assert str(row["id"]) == out["image_id"]
    assert (row["storage_bucket"], row["storage_path"], row["sha256"], row["content_type"]) == (
        "catalog", f"products/{pid}/{_sha(data)}.png", _sha(data), "image/png")
    assert (row["status"], row["source"], row["caption_es"], row["sort_order"]) == (
        "confirmed", "upload", "Vista frontal", 0)
    assert str(row["created_by_operator_id"]) == db_operator.operator_id
    [(seq, event_type, payload, actor_kind, actor)] = _events(dsn, pid)
    assert (seq, event_type, actor_kind, actor) == (1, "product.image_added", "operator", db_operator.operator_id)
    assert payload == {"image_id": out["image_id"], "sha256": _sha(data), "content_type": "image/png",
                       "source": "upload"}


@needs_db
def test_a_second_image_goes_after_the_first(disposable_database, db_operator) -> None:
    dsn = disposable_database
    pid = _product(dsn)
    _add(dsn, db_operator, pid, _png(20))
    _add(dsn, db_operator, pid, _jpeg(21), "image/jpeg")
    assert [r["sort_order"] for r in _images(dsn, pid)] == [0, 1]


@needs_db
def test_the_same_image_twice_is_already_present(disposable_database, db_operator) -> None:
    dsn = disposable_database
    pid = _product(dsn)
    first = _add(dsn, db_operator, pid, _png(30), caption_es="uno")
    again = _add(dsn, db_operator, pid, _png(30), caption_es="otra leyenda")  # a new key: not a replay
    assert again["already_present"] is True and again["replayed"] is False
    assert again["image_id"] == first["image_id"] and again["version"] == 1
    assert len(_images(dsn, pid)) == 1
    assert [e[1] for e in _events(dsn, pid)] == ["product.image_added"]
    # The same bytes on another product are that product's own image.
    other = _product(dsn)
    assert _add(dsn, db_operator, other, _png(30))["already_present"] is False


@needs_db
def test_a_replay_returns_the_first_answer(disposable_database, db_operator) -> None:
    dsn = disposable_database
    pid = _product(dsn)
    key = uuid.uuid4().hex
    first = _add(dsn, db_operator, pid, _png(40), key=key)
    replay = _add(dsn, db_operator, pid, _png(40), key=key)
    assert replay["replayed"] is True and replay["image_id"] == first["image_id"]
    with pytest.raises(CommandRefused) as exc:  # same key, different image
        _add(dsn, db_operator, pid, _png(41), key=key)
    assert exc.value.code == "idempotency_key_reused"


@needs_db
def test_add_image_refusals(disposable_database, db_operator) -> None:
    dsn = disposable_database
    with pytest.raises(CommandRefused) as exc:
        _add(dsn, db_operator, str(uuid.uuid4()), _png(50))
    assert (exc.value.status_code, exc.value.code) == (404, "product_not_found")
    pid = _product(dsn)
    for extra in ({"caption_es": "Foto de Labdelivery"}, {"source_url": "https://lab-delivery.example/x.png"}):
        with pytest.raises(CommandRefused) as exc:
            _add(dsn, db_operator, pid, _png(51), **extra)
        assert (exc.value.status_code, exc.value.code) == (422, "labdelivery_refused")
    assert _images(dsn, pid) == [] and _events(dsn, pid) == []


@needs_db
def test_update_product_image_changes_status_caption_and_order(disposable_database, db_operator) -> None:
    from origenlab_api.v2.catalog.reads import V2CatalogReads

    dsn = disposable_database
    pid = _product(dsn)
    image_id = _add(dsn, db_operator, pid, _png(60), caption_es="Frontal")["image_id"]
    out = _update(dsn, db_operator, {"image_id": image_id, "expected_version": 1, "status": "hidden",
                                     "caption_es": "Lateral", "sort_order": 3, "note": "foto repetida"})
    assert (out["version"], out["product_id"], out["image_id"]) == (2, pid, image_id)
    [row] = _images(dsn, pid)
    assert (row["status"], row["caption_es"], row["sort_order"], row["version"]) == ("hidden", "Lateral", 3, 2)
    [_, (seq, event_type, payload, actor_kind, actor)] = _events(dsn, pid)
    assert (seq, event_type, actor_kind, actor) == (2, "product.image_updated", "operator", db_operator.operator_id)
    assert payload["image_id"] == image_id and sorted(payload["changed"]) == ["caption_es", "sort_order", "status"]
    assert payload["status"] == "hidden" and payload["note"] == "foto repetida"
    reads = V2CatalogReads(psycopg.connect, runtime_dsn(dsn))
    assert reads.product_detail(uuid.UUID(pid))["images"] == []  # hidden from the detail
    found = reads.image(uuid.UUID(image_id))
    assert found["status"] == "hidden" and found["storage_path"] == row["storage_path"]
    assert found["product_id"] == pid
    assert reads.image(uuid.uuid4()) is None
    # A blank caption clears it; confirming shows the image again.
    _update(dsn, db_operator, {"image_id": image_id, "expected_version": 2, "caption_es": "  ", "status": "confirmed"})
    [row] = _images(dsn, pid)
    assert (row["caption_es"], row["status"], row["version"]) == (None, "confirmed", 3)
    assert len(reads.product_detail(uuid.UUID(pid))["images"]) == 1


@needs_db
def test_update_product_image_refusals(disposable_database, db_operator) -> None:
    dsn = disposable_database
    pid = _product(dsn)
    image_id = _add(dsn, db_operator, pid, _png(70), caption_es="Frontal")["image_id"]
    cases = [
        ({"image_id": image_id, "expected_version": 9, "status": "hidden"}, 409, "stale_version"),
        ({"image_id": image_id, "expected_version": 1, "caption_es": "Frontal", "status": "confirmed"},
         422, "no_changes"),
        ({"image_id": image_id, "expected_version": 1}, 422, "no_changes"),
        ({"image_id": str(uuid.uuid4()), "expected_version": 1, "status": "hidden"}, 404, "image_not_found"),
        ({"image_id": image_id, "expected_version": 1, "caption_es": "de Labdelivery"}, 422, "labdelivery_refused"),
    ]
    for raw, status, code in cases:
        with pytest.raises(CommandRefused) as exc:
            _update(dsn, db_operator, raw)
        assert (exc.value.status_code, exc.value.code) == (status, code), raw
    assert [r["version"] for r in _images(dsn, pid)] == [1]
    assert [e[1] for e in _events(dsn, pid)] == ["product.image_added"]


def _ungranted_locks(dsn: str) -> int:
    with psycopg.connect(dsn, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("select count(*) from pg_locks where not granted")
        return cur.fetchone()[0]


@needs_db
def test_concurrent_images_on_one_product_take_consecutive_event_positions(disposable_database, db_operator) -> None:
    """Two uploads and an update on one product while a third transaction holds the product: all
    three wait on the product row (the stream owner), then append one after the other."""
    dsn = disposable_database
    pid = _product(dsn)
    image_id = _add(dsn, db_operator, pid, _png(80))["image_id"]
    results: dict[str, object] = {}

    def run(name, fn) -> None:
        try:
            results[name] = fn()
        except Exception as exc:  # noqa: BLE001 - the assertion below names it
            results[name] = exc

    jobs = {
        "a": lambda: _add(dsn, db_operator, pid, _png(81)),
        "b": lambda: _add(dsn, db_operator, pid, _png(82)),
        "u": lambda: _update(dsn, db_operator, {"image_id": image_id, "expected_version": 1, "sort_order": 5}),
    }
    with psycopg.connect(dsn) as holder, holder.cursor() as cur:
        cur.execute("set role origenlab_owner")
        cur.execute("select id from catalog.product where id = %s for update", (pid,))
        threads = [threading.Thread(target=run, args=item) for item in jobs.items()]
        for t in threads:
            t.start()
        deadline = time.monotonic() + 10
        while _ungranted_locks(dsn) < 3 and time.monotonic() < deadline:
            time.sleep(0.05)
        assert _ungranted_locks(dsn) >= 3 and all(t.is_alive() for t in threads)
        holder.commit()
    for t in threads:
        t.join(timeout=30)
    assert all(isinstance(r, dict) and r["ok"] for r in results.values()), results
    events = _events(dsn, pid)
    assert [e[0] for e in events] == [1, 2, 3, 4]
    assert sorted(e[1] for e in events[1:]) == ["product.image_added", "product.image_added", "product.image_updated"]
    assert len(_images(dsn, pid)) == 3


@needs_db
def test_upload_end_to_end_through_the_route(disposable_database, db_operator) -> None:
    """Route → FakeStorage → the real command transaction → the real read, with a replayed key."""
    from origenlab_api.v2.catalog.commands import V2CatalogRepository
    from origenlab_api.v2.catalog.reads import V2CatalogReads
    from origenlab_api.v2.catalog.routes import catalog_command_router, catalog_read_router

    dsn = disposable_database
    pid = _product(dsn)
    app = FastAPI()
    register_exception_handlers(app)
    app.include_router(catalog_read_router)
    app.include_router(catalog_command_router)
    app.state.catalog_storage = FakeStorage()
    app.state.catalog_repository = V2CatalogRepository(psycopg.connect, runtime_dsn(dsn))
    app.state.catalog_reads = V2CatalogReads(psycopg.connect, runtime_dsn(dsn))
    app.state.v2_identity = LocalDevIdentity(LOOPBACK, _Lookup(db_operator))
    client = TestClient(app)
    headers = _ikey()
    data = _webp(90)
    first = client.post("/v2/commands/add-product-image", headers=headers, data={"product_id": pid},
                        files={"file": ("foto.webp", data, "image/webp")})
    assert first.status_code == 200, first.text
    replay = client.post("/v2/commands/add-product-image", headers=headers, data={"product_id": pid},
                         files={"file": ("foto.webp", data, "image/webp")})
    assert replay.json()["replayed"] is True and replay.json()["image_id"] == first.json()["image_id"]
    assert list(app.state.catalog_storage.objects) == [f"products/{pid}/{_sha(data)}.webp"]
    r = client.get(f"/v2/catalog/images/{first.json()['image_id']}/url", headers=HEADERS)
    assert r.status_code == 200 and r.json()["expires_in"] == 600
    assert f"products/{pid}/{_sha(data)}.webp" in r.json()["url"]
