"""Quotation-document identity audit: what each PDF itself says, classified read-only.

Every PDF here is generated by the test with invented text (`example.cl`, made-up people and
RUTs). Nothing comes from the real staging.
"""

from __future__ import annotations

import ast
import csv
import hashlib
import http.client
import importlib.util
import json
import threading
from http.server import ThreadingHTTPServer
from pathlib import Path

import fitz
import pytest

from origenlab_api.v2 import quote_document_identity as qd
from origenlab_api.v2 import quote_evidence_review as qr

_API_ROOT = Path(__file__).resolve().parents[1]
_MODULE = _API_ROOT / "src/origenlab_api/v2/quote_document_identity.py"
_CLI = _API_ROOT / "scripts/quote_document_identity.py"
_REVIEW = _API_ROOT / "scripts/quote_evidence_review.py"

QUEUE_FIELDS = [
    "email_id", "tier", "direction_hint", "sent_at", "gmail_message_id",
    "proposed_quote_numbers", "n_documents", "all_bytes_verified", "filenames",
    "same_number_other_emails", "cross_era_number_collision", "queue",
]

# An issuer header that carries its own RUT and address: never a client anchor.
HEADER = [
    "Proveedor Ejemplo Ltda. - Equipos para laboratorio",
    "Casa Matriz: Calle Inventada 123, Ciudad Ficticia",
    "RUT: 99.999.999-9",
    "",
]


def _quote(number: str, addressee: str, *, date: str = "Valdivia, 18 de marzo del 2026",
           rut: str | None = None, address: str | None = None, model: str = "Osmometro modelo X-100") -> list[str]:
    lines = [*HEADER, date, f"COTIZACIÓN N° {number}", f"At. {addressee}"]
    if rut:
        lines.append(f"RUT: {rut}")
    if address:
        lines.append(f"Dirección: {address}")
    return lines + ["", "Item    Ref.    Detalle    Valor unitario    Total",
                    f"1    X100    {model}, fabricante de ejemplo    $ 1.000    $ 1.000",
                    "Condiciones comerciales", "Plazo de entrega 2 semanas"]


BROCHURE = [
    "Folleto tecnico de ejemplo para un osmometro de laboratorio",
    "Rango de medicion 0 a 2000 mosm por kilogramo de agua",
    "Pantalla, memoria, interfaz USB y accesorios incluidos",
]


def _pdf(path: Path, lines: list[str]) -> Path:
    doc = fitz.open()
    page = doc.new_page()
    y = 60
    for line in lines:
        if line:
            page.insert_text((40, y), line, fontsize=9)
        y += 13
    doc.save(path)
    doc.close()
    return path


def _blank_pdf(path: Path) -> Path:
    doc = fitz.open()
    doc.new_page()
    doc.save(path)
    doc.close()
    return path


class World:
    """An invented staging directory: emails, their documents, and the files themselves."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.docs_root = root / "audits"
        self.docs_dir = self.docs_root / "docs"
        self.docs_dir.mkdir(parents=True)
        self.staging_dir = self.docs_root / "staging"
        self.records: list[dict] = []
        self.queue: list[dict] = []
        self._att = 0

    def file(self, name: str, lines: list[str] | None) -> tuple[str, str, Path]:
        tmp = self.root / f"tmp-{len(list(self.root.iterdir()))}.pdf"
        _pdf(tmp, lines) if lines is not None else _blank_pdf(tmp)
        return self.add_bytes(name, tmp.read_bytes())

    def add_bytes(self, name: str, data: bytes) -> tuple[str, str, Path]:
        sha = hashlib.sha256(data).hexdigest()
        path = self.docs_dir / f"{sha}.pdf"
        path.write_bytes(data)
        return name, sha, path

    def email(self, email_id: int, docs: list[tuple[str, str, Path]], *, thread: str | None = None,
              proposed: list[str] | None = None, recipients: str = "Compras <compras@cliente.example.cl>",
              subject: str = "Cotización") -> None:
        gid = f"19d{email_id:013d}"
        if proposed is None:
            proposed = sorted({f"CN{int(m.group('serial')):05d}" for n, _, _ in docs
                               for m in qd._FILENAME_CN_RE.finditer(n)})
        documents = []
        for name, sha, _ in docs:
            self._att += 1
            documents.append({
                "source_email_id": email_id, "source_attachment_id": self._att, "filename": name,
                "sha256": sha, "bytes_hash_verified": True,
                "cn_tokens": [f"CN{int(m.group('serial')):05d}" for m in qd._FILENAME_CN_RE.finditer(name)],
                "stored_path": f"docs/{sha}.pdf",
            })
        self.records.append({
            "kind": "gmail_message", "dedupe_key": f"gmail_message:{gid}", "source_uri": f"gmail://msg/{gid}",
            "payload": {
                "source_email_id": email_id, "direction_hint": "customer_quote_candidate",
                "sent_at": f"2026-03-{10 + email_id % 10:02d}T10:00:00-03:00", "subject_raw": subject,
                "sender": "Ventas <ventas@example.cl>", "recipients": recipients,
                "rfc822_message_id": f"<{email_id}@mail.example.cl>", "gmail_message_id": gid,
                "gmail_thread_id": thread or f"t{email_id}", "gmail_label_ids": ["SENT"],
                "raw_sha256": hashlib.sha256(gid.encode()).hexdigest(),
                "documents": documents, "proposed_quote_numbers": proposed,
            },
        })
        self.queue.append({
            "email_id": str(email_id), "gmail_message_id": gid, "proposed_quote_numbers": " ".join(proposed),
            "same_number_other_emails": "", "cross_era_number_collision": "False",
            "queue": "Q1_gmail_single_cn" if len(proposed) == 1 else "Q2_gmail_zero_or_multiple_cn",
        })

    def write(self) -> qr.Staging:
        self.staging_dir.mkdir(exist_ok=True)
        (self.staging_dir / qr.SOURCE_RECORDS_FILE).write_text(json.dumps(self.records, ensure_ascii=False),
                                                              encoding="utf-8")
        with (self.staging_dir / qr.QUEUE_FILE).open("w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=QUEUE_FIELDS, restval="")
            w.writeheader()
            w.writerows(self.queue)
        return qr.load_staging(self.staging_dir)

    def audit(self, ocr=None) -> tuple[dict, dict[int, dict]]:
        staging = self.write()
        docs = qd.audit_documents(staging, self.docs_root, ocr=ocr)
        report = qd.build_report(staging, docs, generated_at="2026-09-24T00:00:00+00:00")
        return report, {c["email_id"]: c for c in report["candidates"]}


def _rel(cands: dict[int, dict], a: int, b: int) -> dict:
    return next(r for r in cands[a]["relations"] if r["other_email_id"] == b)


def _no_ocr(path: Path) -> str:
    raise AssertionError(f"OCR must not run on a PDF with a text layer: {path}")


@pytest.fixture
def world(tmp_path: Path) -> World:
    return World(tmp_path)


# --- the seven cases -------------------------------------------------------------------


def test_bioeq_vs_instafarm_is_different_explicit_client_even_with_a_shared_brochure(world) -> None:
    brochure = world.file("Leaflet-Ejemplo.PDF", BROCHURE)
    world.email(1, [world.file("CN01005-Bioeq SpA.pdf", _quote("1005-26", "Bioeq SpA")), brochure])
    world.email(2, [world.file("Cotización 1006- Ana Prueba - InstaFarm.pdf",
                               _quote("1006-26", "Ana Prueba - InstaFarm")), brochure], proposed=[])
    report, c = world.audit(ocr=_no_ocr)

    rel = _rel(c, 1, 2)
    assert rel["classification"] == qd.DIFFERENT_EXPLICIT_CLIENT
    # The only link is the brochure's bytes, and it is named as such — not as a client link.
    assert rel["links"] == ["shared_generic_document"]
    evidence = [x for p in rel["document_pairs"] for x in p["evidence"]]
    assert "At. Bioeq SpA" in evidence and "At. Ana Prueba - InstaFarm" in evidence
    docs = {d["sha256"]: d for d in report["documents"]}
    assert docs[brochure[1]]["document_class"] == qd.BROCHURE_OR_GENERIC
    insta = next(d for d in report["documents"] if "InstaFarm" in d["filenames"][0])
    assert insta["clients"][0]["contact"] == "Ana Prueba"
    assert insta["clients"][0]["organization"] == "InstaFarm"
    assert c[2]["document_quote_numbers"] == ["1006-26"]
    # The filename proposed nothing; the document prints 1006-26 — shown for review.
    assert qd.REVIEW_PROPOSAL_DISAGREES in c[2]["review_reasons"]


def test_eurofarma_document_printing_two_numbers_stays_with_a_human(world) -> None:
    two = _quote("1007-26", "Ana Prueba - Eurofarma")
    two.insert(6, "COTIZACIÓN N° 1010-26")
    world.email(1, [world.file("CN1010-Ana Prueba - Eurofarma.pdf", two)])
    world.email(2, [world.file("CN1010-Ana Prueba - Eurofarma v2.pdf", _quote("1010-26", "Ana Prueba - Eurofarma"))])
    report, c = world.audit(ocr=_no_ocr)

    doc = next(d for d in report["documents"] if d["email_ids"] == [1])
    assert doc["quote_number"] is None
    assert [q["raw"] for q in doc["quote_numbers_found"]] == ["1007-26", "1010-26"]
    assert qd.REVIEW_QUOTE_NUMBER_CONFLICT in doc["review_reasons"]
    assert c[1]["needs_human_review"]
    # Same explicit client, but the numbers cannot be compared: never "same quote".
    rel = _rel(c, 1, 2)
    assert rel["classification"] == qd.INSUFFICIENT_EVIDENCE
    assert rel["needs_human_review"] is True


def test_eurofarma_filename_number_contradicting_the_text_is_not_trusted(world) -> None:
    world.email(1, [world.file("CN1010-Ana Prueba - Eurofarma.pdf", _quote("1011-26", "Ana Prueba - Eurofarma"))])
    report, c = world.audit(ocr=_no_ocr)
    doc = report["documents"][0]
    assert doc["quote_number"] is None
    assert qd.REVIEW_FILENAME_NUMBER_MISMATCH in doc["review_reasons"]
    assert any("1011-26" in x for x in doc["classification_evidence"])
    assert c[1]["needs_human_review"]


def test_one_number_printed_for_two_different_clients_is_conflicting(world) -> None:
    world.email(1, [world.file("CN01046-a.pdf", _quote("01046-26", "Ana Prueba - Eurofarma"))])
    world.email(2, [world.file("CN01046-b.pdf", _quote("01046-26", "Luis Ejemplo - Universidad Inventada"))])
    _, c = world.audit(ocr=_no_ocr)
    assert _rel(c, 1, 2)["classification"] == qd.CONFLICTING_CLIENT_EVIDENCE
    assert c[1]["classification"] == qd.CONFLICTING_CLIENT_EVIDENCE
    assert qd.REVIEW_CLIENT_CONFLICT in c[1]["review_reasons"]


def test_duplicate_pdfs_are_one_document_by_sha256(world) -> None:
    quote = world.file("CN01005-Bioeq SpA.pdf", _quote("1005-26", "Bioeq SpA"))
    renamed = ("reenvío cotización.pdf", quote[1], quote[2])  # same bytes, other filename
    world.email(1, [quote], thread="t-a")
    world.email(2, [renamed], thread="t-b", proposed=["CN01005"])
    report, c = world.audit(ocr=_no_ocr)
    assert len(report["documents"]) == 1
    assert report["documents"][0]["email_ids"] == [1, 2]
    assert sorted(report["documents"][0]["filenames"]) == ["CN01005-Bioeq SpA.pdf", "reenvío cotización.pdf"]
    rel = _rel(c, 1, 2)
    assert rel["classification"] == qd.EXACT_DUPLICATE
    assert rel["document_pairs"][0]["evidence"] == [f"sha256 {quote[1]}"]
    assert c[1]["classification"] == c[2]["classification"] == qd.EXACT_DUPLICATE


def test_shared_brochure_only_identifies_nobody(world) -> None:
    brochure = world.file("Leaflet-Ejemplo.PDF", BROCHURE)
    world.email(1, [brochure], proposed=[], recipients="Uno <a@same.example.cl>")
    world.email(2, [brochure], proposed=[], recipients="Dos <b@same.example.cl>")
    report, c = world.audit(ocr=_no_ocr)
    assert c[1]["classification"] == c[2]["classification"] == qd.BROCHURE_OR_GENERIC
    rel = _rel(c, 1, 2)
    assert rel["classification"] == qd.BROCHURE_OR_GENERIC
    assert rel["links"] == ["shared_generic_document"]
    assert report["documents"][0]["clients"] == []


def test_missing_client_name_is_insufficient_evidence(world) -> None:
    lines = [ln for ln in _quote("1042-26", "unused") if not ln.startswith("At.")]
    world.email(1, [world.file("CN1042-26-UP400St.pdf", lines)])
    report, c = world.audit(ocr=_no_ocr)
    doc = report["documents"][0]
    assert doc["document_class"] == qd.INSUFFICIENT_EVIDENCE
    assert qd.REVIEW_NO_CLIENT_ANCHOR in doc["review_reasons"]
    assert c[1]["classification"] == qd.INSUFFICIENT_EVIDENCE
    # The issuer header's RUT and address are not a client.
    assert doc["clients"] == []


def test_ocr_failure_is_recorded_and_insufficient(world) -> None:
    world.email(1, [world.file("CN01200-escaneo.pdf", None)])
    calls: list[Path] = []

    def failing_ocr(path: Path) -> str:
        calls.append(path)
        raise RuntimeError("tesseract exploded")

    report, c = world.audit(ocr=failing_ocr)
    doc = report["documents"][0]
    assert len(calls) == 1
    assert doc["extraction_method"] == qd.METHOD_OCR_FAILED
    assert "tesseract exploded" in doc["extraction_detail"]
    assert doc["document_class"] == qd.INSUFFICIENT_EVIDENCE
    assert qd.REVIEW_NO_TEXT in doc["review_reasons"]
    assert c[1]["classification"] == qd.INSUFFICIENT_EVIDENCE
    assert c[1]["needs_human_review"]


def test_ocr_runs_only_without_a_text_layer_and_its_text_is_used(world) -> None:
    world.email(1, [world.file("CN01201-escaneo.pdf", None)])
    world.email(2, [world.file("CN01202-texto.pdf", _quote("1202-26", "Clínica Inventada SpA"))])
    calls: list[Path] = []

    def fake_ocr(path: Path) -> str:
        calls.append(path)
        return "\n".join(_quote("1201-26", "Clínica Inventada SpA"))

    report, c = world.audit(ocr=fake_ocr)
    assert len(calls) == 1
    scanned = next(d for d in report["documents"] if d["email_ids"] == [1])
    assert scanned["extraction_method"] == qd.METHOD_OCR
    assert scanned["document_class"] == qd.DOC_QUOTATION
    assert _rel(c, 1, 2)["classification"] == qd.SAME_CLIENT_DIFFERENT_QUOTE


def test_same_client_with_two_different_quote_numbers(world) -> None:
    world.email(1, [world.file("CN01007-a.pdf", _quote("1007-26", "Ana Prueba - Eurofarma"))], thread="t-x")
    world.email(2, [world.file("CN01010-b.pdf", _quote("1010-26", "Ana Prueba - EUROFARMA S.A."))], thread="t-y")
    # And one message carrying both quotations at once.
    world.email(3, [world.file("CN01011-c.pdf", _quote("1011-26", "Ana Prueba - Eurofarma")),
                    world.file("Cotización 1012 - d.pdf", _quote("1012-26", "Ana Prueba - Eurofarma"))])
    _, c = world.audit(ocr=_no_ocr)
    rel = _rel(c, 1, 2)
    assert rel["classification"] == qd.SAME_CLIENT_DIFFERENT_QUOTE
    assert rel["links"] == ["client"]  # the printed client, not a domain or thread
    assert rel["document_pairs"][0]["anchor"] == "organization"
    assert c[3]["classification"] == qd.SAME_CLIENT_DIFFERENT_QUOTE
    assert c[3]["document_quote_numbers"] == ["1011-26", "1012-26"]
    assert qd.REVIEW_SEVERAL_QUOTES in c[3]["review_reasons"]
    # Separate quote candidates: nothing merged into one.
    assert len(c[3]["documents"]) == 2


def test_same_client_same_number_different_bytes_is_the_same_quote(world) -> None:
    world.email(1, [world.file("CN01020-a.pdf", _quote("1020-26", "Laboratorio Inventado Ltda."))])
    world.email(2, [world.file("CN01020-a rev.pdf", _quote("1020-26", "LABORATORIO INVENTADO LIMITADA",
                                                           model="Osmometro modelo X-200"))])
    _, c = world.audit(ocr=_no_ocr)
    assert _rel(c, 1, 2)["classification"] == qd.SAME_CLIENT_SAME_QUOTE


# --- what never makes an identity -------------------------------------------------------


def test_identity_never_comes_from_domain_filename_or_subject(world) -> None:
    # Same recipient domain, same subject, same organization in the filename — but the PDFs
    # name different clients. The PDFs win; the domain and subject link nothing.
    world.email(1, [world.file("CN01030-Bioeq SpA.pdf", _quote("1030-26", "Bioeq SpA"))],
                recipients="x <x@shared.example.cl>", subject="Cotización osmómetro")
    world.email(2, [world.file("CN01031-Bioeq SpA.pdf", _quote("1031-26", "Otra Empresa SpA"))],
                recipients="y <y@shared.example.cl>", subject="Cotización osmómetro")
    _, c = world.audit(ocr=_no_ocr)
    assert c[1]["relations"] == [] and c[2]["relations"] == []
    assert c[1]["classification"] == c[2]["classification"] == qd.UNIQUE_EXPLICIT_QUOTE


def test_similar_names_are_not_the_same_client(world) -> None:
    world.email(1, [world.file("CN01040-a.pdf", _quote("1040-26", "Bioeq SpA"))], thread="t")
    world.email(2, [world.file("CN01041-b.pdf", _quote("1041-26", "Bioeqq SpA"))], thread="t")
    _, c = world.audit(ocr=_no_ocr)
    rel = _rel(c, 1, 2)
    assert rel["links"] == ["thread"]
    assert rel["classification"] == qd.DIFFERENT_EXPLICIT_CLIENT


def test_normalization_is_for_comparison_only_and_originals_are_kept() -> None:
    assert qd.normalize_client_name("  BIOEQ  S.p.A. ") == qd.normalize_client_name("Bioeq SpA") == "bioeq"
    assert qd.normalize_client_name("Pontificia Universidad Católica de Chile") == \
        "pontificia universidad catolica de chile"
    assert qd.normalize_client_name("Laboratorio Inventado Limitada") == "laboratorio inventado"
    fields = qd.extract_fields("\n".join(_quote("1005-26", "Álvaro Núñez - BIOEQ S.p.A.", rut="76.123.456-7")))
    anchor = fields.clients[0]
    assert anchor.addressee.line == "At. Álvaro Núñez - BIOEQ S.p.A."
    assert anchor.contact == "Álvaro Núñez" and anchor.organization == "BIOEQ S.p.A."
    assert anchor.rut and anchor.rut.value == "76.123.456-7" and anchor.rut_key == "76123456-7"


def test_rut_decides_when_both_documents_print_one() -> None:
    def doc(addressee: str, rut: str) -> qd.ClientAnchor:
        return qd.extract_fields("\n".join(_quote("1-26", addressee, rut=rut))).clients[0]

    assert qd.compare_clients(doc("Empresa Uno SpA", "76.000.001-1"), doc("EMPRESA UNO", "76000001-1"))[0] == qd.SAME
    assert qd.compare_clients(doc("Empresa Uno SpA", "76.000.001-1"), doc("Empresa Uno SpA", "76.000.002-2"))[0] == \
        qd.CONFLICT
    # A person-only anchor cannot be compared with an organization.
    person = qd.extract_fields("At. Ana Prueba").clients[0]
    assert person.organization is None
    assert qd.compare_clients(person, doc("Empresa Uno SpA", "76.000.001-1"))[0] == qd.INCOMPARABLE


def test_fields_carry_the_exact_lines(world) -> None:
    world.email(1, [world.file("CN01050-x.pdf", _quote("01050-26", "Luis Ejemplo - Universidad Inventada",
                                                       rut="70.000.000-0", address="Av. Ficticia 10"))])
    report, _ = world.audit(ocr=_no_ocr)
    d = report["documents"][0]
    assert d["quote_number"]["raw"] == "01050-26" and d["quote_number"]["key"] == "1050-26"
    assert d["quote_number"]["evidence"]["line"] == "COTIZACIÓN N° 01050-26"
    assert d["document_date"]["value"] == "2026-03-18"
    assert d["document_date"]["line"] == "Valdivia, 18 de marzo del 2026"
    cl = d["clients"][0]
    assert cl["organization"] == "Universidad Inventada" and cl["contact"] == "Luis Ejemplo"
    assert cl["rut"]["value"] == "70.000.000-0" and cl["address"]["value"] == "Av. Ficticia 10"
    assert d["products"][0]["value"].startswith("X-100")
    # The en dash the real template uses separates contact and organization too.
    en = qd.extract_fields("At. Luis Ejemplo – Universidad Inventada").clients[0]
    assert (en.contact, en.organization) == ("Luis Ejemplo", "Universidad Inventada")
    # A hyphenated surname is not a separator.
    hy = qd.extract_fields("At. Luis Pérez-García").clients[0]
    assert (hy.contact, hy.organization, hy.addressee.value) == (None, None, "Luis Pérez-García")


# --- read-only boundary, reports and page ---------------------------------------------


def test_module_imports_no_database_driver_or_network_client() -> None:
    tree = ast.parse(_MODULE.read_text(encoding="utf-8"))
    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported |= {a.name for a in node.names}
        elif isinstance(node, ast.ImportFrom):
            imported.add(node.module or "")
    forbidden = ("psycopg", "sqlite3", "sqlalchemy", "origenlab_api.v2.repository",
                 "origenlab_api.v2.command", "origenlab_api.v2.case_command", "googleapiclient",
                 "requests", "httpx", "urllib")
    assert not [m for m in imported if m.startswith(forbidden)], imported


def _load_script(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _tree(root: Path) -> dict[str, str]:
    return {str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(root.rglob("*")) if p.is_file()}


def test_cli_writes_csv_json_and_texts_and_touches_nothing_else(world, tmp_path: Path) -> None:
    brochure = world.file("Leaflet-Ejemplo.PDF", BROCHURE)
    world.email(1, [world.file("CN01005-Bioeq SpA.pdf", _quote("1005-26", "Bioeq SpA")), brochure])
    world.email(2, [world.file("CN01006-x.pdf", _quote("1006-26", "Ana Prueba - InstaFarm")), brochure])
    world.write()
    ledger = world.docs_root / "review" / "decisions.jsonl"
    ledger.parent.mkdir()
    ledger.write_text('{"email_id": 1, "decision": "leave_pending"}\n', encoding="utf-8")
    before = _tree(world.docs_root)

    cli = _load_script(_CLI, "quote_document_identity_cli")
    out = tmp_path / "identity"
    report = cli.run(world.staging_dir, world.docs_root, out, [1, 2, 999], ocr=False)

    assert _tree(world.docs_root) == before  # staging, documents and ledger untouched
    assert sorted(p.name for p in out.iterdir()) == [cli.REPORT_CSV, cli.REPORT_JSON, cli.TEXTS_DIR]
    assert len(list((out / cli.TEXTS_DIR).iterdir())) == 3
    assert json.loads((out / cli.REPORT_JSON).read_text(encoding="utf-8"))["summary"] == report["summary"]
    rows = list(csv.DictReader((out / cli.REPORT_CSV).open(encoding="utf-8")))
    assert {r["email_id"] for r in rows} == {"1", "2"}
    assert any(r["addressee_line"] == "At. Bioeq SpA" for r in rows)
    assert report["focus"][2] == {"email_id": 999, "classification": None, "review_reasons": ["not_staged"]}
    assert (out / cli.REPORT_JSON).stat().st_mode & 0o077 == 0

    with pytest.raises(SystemExit, match="not empty"):
        cli.run(world.staging_dir, world.docs_root, out, [], ocr=False)
    with pytest.raises(SystemExit, match="outside the staging"):
        cli.run(world.staging_dir, world.docs_root, world.staging_dir / "x", [], ocr=False)


@pytest.fixture
def page_server(world, tmp_path: Path):
    brochure = world.file("Leaflet-Ejemplo.PDF", BROCHURE)
    quote = world.file("CN01005-Bioeq SpA.pdf", _quote("1005-26", "Bioeq SpA"))
    world.email(1, [quote, brochure])
    world.email(2, [world.file("CN01006-x.pdf", _quote("1006-26", "Ana Prueba - InstaFarm")), brochure])
    world.write()
    cli = _load_script(_CLI, "quote_document_identity_cli2")
    out = tmp_path / "identity"
    cli.run(world.staging_dir, world.docs_root, out, [], ocr=False)

    review = _load_script(_REVIEW, "quote_evidence_review_script2")
    staging = qr.load_staging(world.staging_dir)
    ledger = qr.DecisionLedger(tmp_path / "ledger" / "decisions.jsonl")
    httpd = ThreadingHTTPServer(("127.0.0.1", 0), None)
    port = httpd.server_address[1]
    httpd.RequestHandlerClass = review.make_handler(
        staging, ledger, "op@example.cl", port,
        identity=review.load_identity(out), identity_dir=out, documents_root=world.docs_root,
    )
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    yield port, quote, ledger
    httpd.shutdown()


def _get(port: int, path: str) -> tuple[int, bytes, dict]:
    conn = http.client.HTTPConnection("127.0.0.1", port)
    conn.request("GET", path, headers={"Host": f"127.0.0.1:{port}"})
    resp = conn.getresponse()
    return resp.status, resp.read(), dict(resp.getheaders())


def test_review_page_shows_the_summary_and_links_to_document_evidence(page_server) -> None:
    port, quote, ledger = page_server
    status, body, _ = _get(port, "/")
    html = body.decode()
    assert status == 200 and "Identidad de documentos" in html
    assert "different_explicit_client" in html

    status, body, _ = _get(port, "/item/1")
    html = body.decode()
    assert status == 200
    assert "At. Bioeq SpA" in html
    assert f"/doc/{quote[1]}" in html and f"/doc/{quote[1]}/texto" in html
    assert "shared_generic_document" in html

    status, body, headers = _get(port, f"/doc/{quote[1]}")
    assert status == 200 and headers["Content-Type"] == "application/pdf"
    assert hashlib.sha256(body).hexdigest() == quote[1]
    status, body, _ = _get(port, f"/doc/{quote[1]}/texto")
    assert status == 200 and "COTIZACIÓN N° 1005-26" in body.decode()
    assert not ledger.path.exists()


def test_review_page_serves_only_staged_documents(page_server) -> None:
    port, *_ = page_server
    assert _get(port, "/doc/" + "0" * 64)[0] == 404
    assert _get(port, "/doc/../../etc/passwd")[0] == 404
    assert _get(port, "/doc/not-a-sha")[0] == 404
