"""Document-level quotation review: one candidate per exact document, one decision each.

Every PDF is generated by the test with invented text (`example.cl`, made-up people and
numbers), through the identity suite's `World`. Nothing comes from the real staging.
"""

from __future__ import annotations

import ast
import http.client
import importlib.util
import json
import threading
import uuid
from http.server import ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlencode

import pytest
from test_v2_quote_document_identity import BROCHURE, World, _quote

from origenlab_api.v2 import quote_document_identity as qd
from origenlab_api.v2 import quote_document_review as dr
from origenlab_api.v2 import quote_evidence_review as qr

_API_ROOT = Path(__file__).resolve().parents[1]
_MODULE = _API_ROOT / "src/origenlab_api/v2/quote_document_review.py"
_REVIEW = _API_ROOT / "scripts/quote_evidence_review.py"
OPERATOR = "op@example.cl"


@pytest.fixture
def world(tmp_path: Path) -> World:
    return World(tmp_path)


def _review(world: World) -> tuple[qr.Staging, dr.DocumentReview, dict]:
    report, _ = world.audit()
    staging = qr.load_staging(world.staging_dir)
    return staging, dr.build_document_review(staging, report), report


def _two_quote_email(world: World, email_id: int = 1) -> tuple[str, str]:
    """One email, two quotations for the same client, plus a brochure — the 706528 shape."""
    a = world.file("Cotización 1007- Ana Prueba - Eurofarma.pdf", _quote("1007-26", "Ana Prueba - Eurofarma"))
    b = world.file("CN1010-Ana Prueba - Eurofarma.pdf", _quote("1010-26", "Ana Prueba - Eurofarma"))
    world.email(email_id, [a, world.file("Leaflet-Ejemplo.PDF", BROCHURE), b])
    return a[1], b[1]


def _ledger(tmp_path: Path) -> dr.DocumentDecisionLedger:
    return dr.DocumentDecisionLedger(tmp_path / "review" / dr.DOCUMENT_LEDGER_FILE)


def _confirm(review, ledger, sha, **kw):
    kw.setdefault("decision", qr.DECISION_CONFIRM)
    kw.setdefault("operator", OPERATOR)
    return dr.record_document_decision(review, ledger, sha, **kw)


# --- one email, several quotations ------------------------------------------------------


def test_one_email_with_two_quotes_is_two_document_candidates(world) -> None:
    a, b = _two_quote_email(world)
    staging, review, _ = _review(world)

    cands = review.for_email(1)
    assert {c.sha256 for c in cands} == {a, b}  # the brochure is not a candidate
    by_sha = {c.sha256: c for c in cands}
    for sha, number, name in ((a, "1007-26", "Cotización 1007- Ana Prueba - Eurofarma.pdf"),
                              (b, "1010-26", "CN1010-Ana Prueba - Eurofarma.pdf")):
        c = by_sha[sha]
        assert c.filenames == (name,)
        assert c.printed_quote_numbers == (number,)
        assert c.proposed_quote_number == number
        assert c.proposed_status == dr.PROPOSED_QUOTATION
        assert c.client_evidence_lines() == ["At. Ana Prueba - Eurofarma"]
    assert review.quote_document_count(1) == 2

    # One email-level decision cannot pick one of the two quotations.
    email_ledger = qr.DecisionLedger(world.root / "review" / "decisions.jsonl")
    with pytest.raises(qr.ReviewRefused, match="2 quotation documents"):
        qr.record_decision(
            staging, email_ledger, 1, decision=qr.DECISION_CONFIRM, operator=OPERATOR,
            opportunity_mode=qr.OPPORTUNITY_CREATE_NEW, quote_number="CN01010",
            quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL, quote_document_count=2,
        )
    assert email_ledger.entries() == []
    # Saying the message is not a quotation, or leaving it pending, is still an email act.
    qr.record_decision(staging, email_ledger, 1, decision=qr.DECISION_PENDING, operator=OPERATOR,
                       quote_document_count=2)
    assert len(email_ledger.entries()) == 1


def test_same_client_different_numbers_are_decided_separately(world, tmp_path) -> None:
    a, b = _two_quote_email(world)
    _, review, _ = _review(world)
    ca, cb = review.candidate(a), review.candidate(b)
    assert [(r.other_sha256, r.via, r.classification) for r in ca.related] == [
        (b, (dr.VIA_SAME_EMAIL,), qd.SAME_CLIENT_DIFFERENT_QUOTE)
    ]
    assert not ca.review_reasons and not cb.review_reasons

    ledger = _ledger(tmp_path)
    _confirm(review, ledger, a, opportunity_mode=qr.OPPORTUNITY_CREATE_NEW,
             quote_number="1007-26", quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)
    states = ledger.states()
    assert states[a].status == qr.STATUS_CONFIRMED
    assert b not in states  # confirming one quotation says nothing about the other
    dr.record_document_decision(review, ledger, b, decision=qr.DECISION_REJECT, operator=OPERATOR,
                                reason="borrador enviado por error")
    states = ledger.states()
    assert (states[a].status, states[b].status) == (qr.STATUS_CONFIRMED, qr.STATUS_REJECTED)
    # A proposal is the number the document prints — not the other document's.
    with pytest.raises(qr.ReviewRefused, match="not the printed proposal"):
        dr.build_document_decision(cb, decision=qr.DECISION_CONFIRM, operator=OPERATOR,
                                   opportunity_mode=qr.OPPORTUNITY_CREATE_NEW,
                                   quote_number="1007-26", quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)


def test_exact_duplicate_file_across_emails_is_one_canonical_candidate(world, tmp_path) -> None:
    quote = world.file("CN01005-Bioeq SpA.pdf", _quote("1005-26", "Bioeq SpA"))
    renamed = ("reenvío cotización.pdf", quote[1], quote[2])  # same bytes, another name
    # Inserted later-first: the canonical occurrence is chosen by time, not by file order.
    world.email(3, [renamed], thread="t-b", proposed=["CN01005"])
    world.email(1, [quote], thread="t-a")
    world.email(2, [quote], thread="t-a")
    staging, review, _ = _review(world)

    assert len(review.candidates) == 1
    c = review.candidates[0]
    assert c.sha256 == quote[1]
    assert c.canonical.email_id == 1
    assert [o.email_id for o in c.duplicate_occurrences] == [2, 3]
    assert c.filenames == ("CN01005-Bioeq SpA.pdf", "reenvío cotización.pdf")
    # Every occurrence keeps its own exact identifiers.
    for o in c.occurrences:
        item = staging.item(o.email_id)
        assert (o.gmail_message_id, o.rfc822_message_id, o.gmail_thread_id, o.source_record_sha256) == (
            item.gmail_message_id, item.rfc822_message_id, item.gmail_thread_id, item.source_record_sha256)
    assert [review.quote_document_count(e) for e in (1, 2, 3)] == [1, 1, 1]
    assert c.proposed_status == dr.PROPOSED_QUOTATION

    ledger = _ledger(tmp_path)
    entry = _confirm(review, ledger, quote[1], opportunity_mode=qr.OPPORTUNITY_CREATE_NEW,
                     quote_number="1005-26", quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)
    assert entry["canonical_email_id"] == 1
    assert [o["email_id"] for o in entry["occurrences"]] == [1, 2, 3]
    assert len(ledger.states()) == 1  # one document, one status


def test_one_opportunity_with_multiple_quotes(world, tmp_path) -> None:
    a, b = _two_quote_email(world)
    _, review, _ = _review(world)
    ledger = _ledger(tmp_path)

    first = _confirm(review, ledger, a, opportunity_mode=qr.OPPORTUNITY_CREATE_NEW,
                     quote_number="1007-26", quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)
    planned = first["opportunity"]["planned_opportunity_id"]
    assert first["opportunity"] == {"mode": qr.OPPORTUNITY_CREATE_NEW, "opportunity_id": None,
                                    "planned_opportunity_id": planned}
    # A planned id is joined only when typed, and only if a confirmed document holds it.
    with pytest.raises(qr.ReviewRefused, match="no other confirmed document plans"):
        _confirm(review, ledger, b, opportunity_mode=dr.OPPORTUNITY_PLANNED, opportunity_id=str(uuid.uuid4()),
                 quote_number="1010-26", quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)
    second = _confirm(review, ledger, b, opportunity_mode=dr.OPPORTUNITY_PLANNED, opportunity_id=planned,
                      quote_number="1010-26", quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)
    assert second["opportunity"]["planned_opportunity_id"] == planned

    plans = dr.opportunity_plans(review, ledger)
    assert len(plans) == 1
    assert plans[0].opportunity_key == planned and plans[0].mode == dr.OPPORTUNITY_PLANNED
    # One opportunity, two separate quotations.
    assert plans[0].quote_numbers == ("1007-26", "1010-26")
    assert {q.document_sha256 for q in plans[0].quotes} == {a, b}
    assert all(e["applied"] is False for e in ledger.entries())


def test_an_existing_opportunity_can_hold_several_quotes(world, tmp_path) -> None:
    a, b = _two_quote_email(world)
    _, review, _ = _review(world)
    ledger = _ledger(tmp_path)
    opp = str(uuid.uuid4())
    for sha, number in ((a, "1007-26"), (b, "1010-26")):
        _confirm(review, ledger, sha, opportunity_mode=qr.OPPORTUNITY_EXISTING, opportunity_id=opp,
                 quote_number=number, quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)
    (plan,) = dr.opportunity_plans(review, ledger)
    assert (plan.opportunity_key, plan.mode, plan.quote_numbers) == (opp, qr.OPPORTUNITY_EXISTING,
                                                                     ("1007-26", "1010-26"))


# --- conflicts stay with a human ------------------------------------------------------


def test_conflicting_client_names_in_one_email_require_review(world, tmp_path) -> None:
    a = world.file("CN01020-a.pdf", _quote("1020-26", "Ana Prueba - Eurofarma"))
    b = world.file("CN01021-b.pdf", _quote("1021-26", "Luis Ejemplo - Universidad Inventada"))
    world.email(1, [a, b])
    _, review, _ = _review(world)
    for sha in (a[1], b[1]):
        c = review.candidate(sha)
        assert c.proposed_status == dr.NEEDS_REVIEW
        assert c.proposed_quote_number is None
        assert dr.REVIEW_OTHER_CLIENT_SAME_EMAIL in c.review_reasons

    ledger = _ledger(tmp_path)
    with pytest.raises(qr.ReviewRefused, match="no proposed number"):
        _confirm(review, ledger, a[1], opportunity_mode=qr.OPPORTUNITY_CREATE_NEW,
                 quote_number="1020-26", quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)
    with pytest.raises(qr.ReviewRefused, match="needs review"):
        _confirm(review, ledger, a[1], opportunity_mode=qr.OPPORTUNITY_CREATE_NEW,
                 quote_number="1020-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED)
    assert ledger.entries() == []
    entry = _confirm(review, ledger, a[1], opportunity_mode=qr.OPPORTUNITY_CREATE_NEW,
                     quote_number="1020-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED,
                     reason="dos clientes distintos en un correo; este PDF es de Eurofarma")
    assert entry["review_reasons_at_decision"] == [dr.REVIEW_OTHER_CLIENT_SAME_EMAIL]


def test_one_printed_number_for_two_clients_requires_review(world) -> None:
    world.email(1, [world.file("CN01046-a.pdf", _quote("01046-26", "Ana Prueba - Eurofarma"))])
    world.email(2, [world.file("CN01046-b.pdf", _quote("01046-26", "Luis Ejemplo - Universidad Inventada"))])
    _, review, _ = _review(world)
    assert len(review.candidates) == 2
    for c in review.candidates:
        assert c.needs_review and c.proposed_quote_number is None
        assert dr.REVIEW_NUMBER_ON_OTHER_CLIENT in c.review_reasons
        (rel,) = c.related
        assert rel.via == (dr.VIA_PRINTED_NUMBER,)
        assert rel.classification == qd.CONFLICTING_CLIENT_EVIDENCE


def test_conflicting_quote_numbers_require_review(world) -> None:
    two = _quote("1007-26", "Ana Prueba - Eurofarma")
    two.insert(6, "COTIZACIÓN N° 1010-26")
    both = world.file("CN1010-Ana Prueba - Eurofarma.pdf", two)
    mismatch = world.file("CN1012-Ana Prueba - Eurofarma.pdf", _quote("1013-26", "Ana Prueba - Eurofarma"))
    world.email(1, [both])
    world.email(2, [mismatch])
    _, review, _ = _review(world)

    c = review.candidate(both[1])
    assert c.printed_quote_numbers == ("1007-26", "1010-26")
    assert c.proposed_quote_number is None and c.needs_review
    assert qd.REVIEW_QUOTE_NUMBER_CONFLICT in c.review_reasons
    m = review.candidate(mismatch[1])
    assert m.printed_quote_numbers == ("1013-26",)
    assert m.proposed_quote_number is None
    assert qd.REVIEW_FILENAME_NUMBER_MISMATCH in m.review_reasons


def test_same_number_on_two_documents_is_a_resend_only_on_one_opportunity(world, tmp_path) -> None:
    v1 = world.file("CN1010-Ana Prueba - Eurofarma.pdf", _quote("1010-26", "Ana Prueba - Eurofarma"))
    v2 = world.file("CN1010-Ana Prueba - Eurofarma v2.pdf",
                    _quote("1010-26", "Ana Prueba - Eurofarma", model="Osmometro modelo X-200"))
    world.email(1, [v1])
    world.email(2, [v2])
    _, review, _ = _review(world)
    for sha in (v1[1], v2[1]):
        c = review.candidate(sha)
        assert dr.REVIEW_NUMBER_ON_OTHER_DOCUMENT in c.review_reasons
        assert c.related[0].classification == qd.SAME_CLIENT_SAME_QUOTE

    ledger = _ledger(tmp_path)
    opp = str(uuid.uuid4())
    _confirm(review, ledger, v1[1], opportunity_mode=qr.OPPORTUNITY_EXISTING, opportunity_id=opp,
             quote_number="1010-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED, reason="primer envío")
    with pytest.raises(qr.ReviewRefused, match="cannot belong to two opportunities"):
        _confirm(review, ledger, v2[1], opportunity_mode=qr.OPPORTUNITY_CREATE_NEW,
                 quote_number="1010-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED, reason="x")
    with pytest.raises(qr.ReviewRefused, match="needs review"):
        _confirm(review, ledger, v2[1], opportunity_mode=qr.OPPORTUNITY_EXISTING, opportunity_id=opp,
                 quote_number="1010-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED)
    entry = _confirm(review, ledger, v2[1], opportunity_mode=qr.OPPORTUNITY_EXISTING, opportunity_id=opp,
                     quote_number="1010-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED,
                     reason="revisión del mismo presupuesto, cambia el modelo")
    assert entry["same_quote_number_as"] == [v1[1]]


def test_typing_a_number_another_document_holds_needs_a_reason(world, tmp_path) -> None:
    a, b = _two_quote_email(world)  # both proposed: nothing else asks for a reason
    _, review, _ = _review(world)
    ledger = _ledger(tmp_path)
    opp = str(uuid.uuid4())
    _confirm(review, ledger, b, opportunity_mode=qr.OPPORTUNITY_EXISTING, opportunity_id=opp,
             quote_number="1010-26", quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL)
    with pytest.raises(qr.ReviewRefused, match="resend or a revision"):
        _confirm(review, ledger, a, opportunity_mode=qr.OPPORTUNITY_EXISTING, opportunity_id=opp,
                 quote_number="1010-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED)
    assert len(ledger.entries()) == 1


# --- boundaries -------------------------------------------------------------------------


def test_a_report_that_does_not_match_the_staging_is_refused(world) -> None:
    world.email(1, [world.file("CN01005-Bioeq SpA.pdf", _quote("1005-26", "Bioeq SpA"))])
    report, _ = world.audit()
    world.email(2, [world.file("CN01006-x.pdf", _quote("1006-26", "Ana Prueba - InstaFarm"))])
    staging = world.write()  # staging grew; the report did not
    with pytest.raises(qr.StagingInconsistent, match="not in the identity report"):
        dr.build_document_review(staging, report)


def test_document_rows_round_trip_through_the_written_report(world) -> None:
    _two_quote_email(world)
    report, _ = world.audit()
    for d in report["documents"]:
        assert qd.document_from_dict(json.loads(json.dumps(d))).as_dict() == d


def test_module_imports_no_database_driver_or_network_client() -> None:
    tree = ast.parse(_MODULE.read_text(encoding="utf-8"))
    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported |= {a.name for a in node.names}
        elif isinstance(node, ast.ImportFrom):
            imported.add(node.module or "")
    forbidden = ("psycopg", "sqlite3", "sqlalchemy", "origenlab_api.v2.repository",
                 "origenlab_api.v2.command", "origenlab_api.v2.case_command", "googleapiclient",
                 "requests", "httpx", "urllib", "subprocess")
    assert not [m for m in imported if m.startswith(forbidden)], imported


# --- the review page ------------------------------------------------------------------


def _load_script(name: str):
    spec = importlib.util.spec_from_file_location(name, _REVIEW)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture
def doc_server(world, tmp_path: Path):
    a, b = _two_quote_email(world)
    report, _ = world.audit()
    identity_dir = tmp_path / "identity"
    identity_dir.mkdir()
    (identity_dir / "quote_document_identity.json").write_text(json.dumps(report), encoding="utf-8")

    review = _load_script("quote_evidence_review_script_docs")
    staging = qr.load_staging(world.staging_dir)
    ledger = qr.DecisionLedger(tmp_path / "ledger" / "decisions.jsonl")
    httpd = ThreadingHTTPServer(("127.0.0.1", 0), None)
    port = httpd.server_address[1]
    httpd.RequestHandlerClass = review.make_handler(
        staging, ledger, OPERATOR, port, identity=review.load_identity(identity_dir),
        identity_dir=identity_dir, documents_root=world.docs_root,
    )
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    yield port, a, b, ledger, dr.DocumentDecisionLedger(ledger.path.with_name(dr.DOCUMENT_LEDGER_FILE))
    httpd.shutdown()


def _req(port: int, method: str, path: str, body: dict | None = None, origin: str | None = "same"):
    conn = http.client.HTTPConnection("127.0.0.1", port)
    headers = {"Host": f"127.0.0.1:{port}"}
    if origin:
        headers["Origin"] = f"http://127.0.0.1:{port}" if origin == "same" else origin
    data = None
    if body is not None:
        data = urlencode(body)
        headers["Content-Type"] = "application/x-www-form-urlencoded"
    conn.request(method, path, body=data, headers=headers)
    resp = conn.getresponse()
    return resp.status, resp.read().decode("utf-8", "replace"), dict(resp.getheaders())


def test_email_page_lists_each_quote_and_offers_no_email_level_confirm(doc_server) -> None:
    port, a, b, ledger, doc_ledger = doc_server
    status, html, _ = _req(port, "GET", "/item/1", origin=None)
    assert status == 200
    assert f"/documento/{a}" in html and f"/documento/{b}" in html
    assert "1007-26" in html and "1010-26" in html
    assert "value=confirm_customer_quotation" not in html
    status, html, _ = _req(port, "POST", "/item/1/decide", {
        "decision": qr.DECISION_CONFIRM, "opportunity_mode": qr.OPPORTUNITY_CREATE_NEW,
        "quote_number": "CN01010", "quote_number_basis": qr.BASIS_CONFIRMED_PROPOSAL,
    })
    assert status == 422 and "2 quotation documents" in html
    assert not ledger.path.exists() and not doc_ledger.path.exists()


def test_document_page_shows_its_evidence_and_records_its_own_decision(doc_server) -> None:
    port, a, b, ledger, doc_ledger = doc_server
    status, html, _ = _req(port, "GET", f"/documento/{a}", origin=None)
    assert status == 200
    for needle in (a, "Cotización 1007- Ana Prueba - Eurofarma.pdf", "At. Ana Prueba - Eurofarma",
                   "COTIZACIÓN N° 1007-26", "Propuesta", f"/documento/{a}/decide"):
        assert needle in html, needle

    status, _, headers = _req(port, "POST", f"/documento/{a}/decide", {
        "decision": qr.DECISION_CONFIRM, "opportunity_mode": qr.OPPORTUNITY_CREATE_NEW,
        "quote_number": "1007-26", "quote_number_basis": qr.BASIS_CONFIRMED_PROPOSAL,
    })
    assert status == 303 and headers["Location"] == f"/documento/{a}"
    (entry,) = doc_ledger.entries()
    assert (entry["document_sha256"], entry["quote_number"], entry["applied"]) == (a, "1007-26", False)
    assert not ledger.path.exists()  # the email ledger is untouched

    status, html, _ = _req(port, "GET", "/documentos", origin=None)
    assert status == 200 and entry["opportunity"]["planned_opportunity_id"] in html

    # A foreign origin writes nothing; an unknown document is not found.
    status, _, _ = _req(port, "POST", f"/documento/{b}/decide",
                        {"decision": qr.DECISION_PENDING}, origin="http://evil.example")
    assert status == 403
    assert _req(port, "POST", "/documento/" + "0" * 64 + "/decide", {"decision": qr.DECISION_PENDING})[0] == 422
    assert _req(port, "GET", "/documento/" + "0" * 64, origin=None)[0] == 404
    assert len(doc_ledger.entries()) == 1
