"""The quotation review policy: one test per rule, then one regression per audited decision.

Every PDF is generated by the test with invented text (`example.cl`, made-up people, numbers
and RUTs), through the identity suite's `World`. Company names mirror the audited cases only
so each regression reads like the decision it protects. Nothing comes from the real staging.
"""

from __future__ import annotations

import ast
import hashlib
import importlib.util
import json
from pathlib import Path

import pytest
from test_v2_quote_document_identity import BROCHURE, HEADER, World, _quote

from origenlab_api.v2 import quote_document_identity as qd
from origenlab_api.v2 import quote_document_review as dr
from origenlab_api.v2 import quote_evidence_review as qr
from origenlab_api.v2 import quote_review_policy as qp
from origenlab_api.v2.quote_confirmation_reconciliation import effective_document_states

_API_ROOT = Path(__file__).resolve().parents[1]
_MODULE = _API_ROOT / "src/origenlab_api/v2/quote_review_policy.py"
_SCRIPT = _API_ROOT / "scripts/quote_review_policy_dryrun.py"

ORIGEN = ["OrigenLab    contacto@example.cl", "Equipos para laboratorio",
          "Casa Matriz: Calle Inventada 51, Ciudad Ficticia", ""]
LABDELIVERY = ["LABDELIVERY - PERSONA INVENTADA", "Giro: Comercialización de Equipos para Laboratorio", ""]
OWN_SENDERS = ("ventas@example.cl",)  # the World's sender: our own invented address
FOREIGN = ["C E R T L A B", "CALIBRACION DE EQUIPOS DE LABORATORIO", ""]


def _oq(number: str, addressee: str, *, header: list[str] = ORIGEN, **kw) -> list[str]:
    """An OrigenLab quotation: the identity suite's layout under OrigenLab's own header."""
    return header + _quote(number, addressee, **kw)[len(HEADER):]


@pytest.fixture
def world(tmp_path: Path) -> World:
    return World(tmp_path)


def _direction(world: World, email_id: int, hint: str) -> None:
    rec = next(r for r in world.records if r["payload"]["source_email_id"] == email_id)
    rec["payload"]["direction_hint"] = hint


def _run(world: World, *, email_ledger: list[dict] | None = None, doc_ledger: list[dict] | None = None):
    report, _ = world.audit()
    staging = qr.load_staging(world.staging_dir)
    review = dr.build_document_review(staging, report)
    issuers = {c.sha256: qp.document_issuer(qd.extract_text(world.docs_dir / f"{c.sha256}.pdf").text)
               for c in review.candidates}
    ledger_dir = world.root / "review"
    ledger_dir.mkdir(exist_ok=True)
    email_path, doc_path = ledger_dir / "decisions.jsonl", ledger_dir / dr.DOCUMENT_LEDGER_FILE
    for path, rows in ((email_path, email_ledger or []), (doc_path, doc_ledger or [])):
        path.write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows), encoding="utf-8")
    email_states = qr.DecisionLedger(email_path).states()
    doc_states = effective_document_states(review, dr.DocumentDecisionLedger(doc_path), email_states)
    return review, qp.dry_run(staging, review, issuers, doc_states, email_states, own_senders=OWN_SENDERS)


def _sha_of(review: dr.DocumentReview, number: str) -> str:
    return next(c.sha256 for c in review.candidates if number in c.printed_quote_numbers)


def _email_decision(email_id: int, decision: str, number: str | None = None, mode: str | None = None) -> dict:
    return {"decision_id": f"d-{email_id}-{decision}", "recorded_at": "2026-09-24T10:00:00+00:00",
            "operator": "op@example.cl", "email_id": email_id, "decision": decision, "quote_number": number,
            "opportunity": {"mode": mode, "opportunity_id": None} if mode else None}


def _doc_decision(sha: str, email_id: int, number: str | None, mode: str = "create_new",
                  decision: str = qr.DECISION_CONFIRM, planned: str = "00000000-0000-4000-8000-000000000001") -> dict:
    return {"target": dr.TARGET_DOCUMENT, "document_sha256": sha, "decision": decision,
            "canonical_email_id": email_id, "quote_number": number,
            "opportunity": ({"mode": mode, "opportunity_id": None, "planned_opportunity_id": planned}
                            if decision == qr.DECISION_CONFIRM else None)}


def _comparison(run: qp.DryRun, key: str) -> qp.LedgerComparison:
    return next(c for c in run.comparison if c.key == key)


# --- the specification ----------------------------------------------------------------


def test_every_rule_names_a_precedent_and_every_reason_names_a_rule() -> None:
    assert [r.id for r in qp.POLICY] == [f"P{n:02d}" for n in range(1, 14)]
    for r in qp.POLICY:
        assert r.title and r.outcome and r.precedent
    reasons = {v for k, v in vars(qp).items() if k.startswith("R_")}
    assert reasons == set(qp.REASON_RULE)
    assert set(qp.REASON_RULE.values()) <= set(qp.RULES)


def test_issuer_is_read_from_the_header_only() -> None:
    assert qp.document_issuer("\n".join(ORIGEN + ["COTIZACIÓN N° 1-26", "At. X"])) == qp.ISSUER_ORIGENLAB
    assert qp.document_issuer("\n".join(LABDELIVERY + ["COTIZACIÓN N° 1-26"])) == qp.ISSUER_LABDELIVERY
    assert qp.document_issuer("\n".join(FOREIGN + ["COTIZACION N°1338/2026"])) == qp.ISSUER_FOREIGN
    # OrigenLab named below the quotation line (a client block, an item) is not the issuer.
    assert qp.document_issuer("\n".join(FOREIGN + ["COTIZACION N°1", "At. OrigenLab"])) == qp.ISSUER_FOREIGN
    assert qp.document_issuer("") == qp.ISSUER_UNKNOWN


def test_quote_numbers_compare_by_serial_letter_and_year() -> None:
    assert qp.same_quote_number("01062-26", "1062-26")
    assert qp.same_quote_number("CN01005", "1005-26")  # a typed CN carries no year
    assert qp.same_quote_number("012092A-26", "12092A-26")
    assert not qp.same_quote_number("012092A-26", "12092-26")
    assert not qp.same_quote_number("011728A-25", "011728A-26")
    assert not qp.same_quote_number(None, "1005-26")


# --- P13 and the rules that keep a document from it -----------------------------------


def test_p13_one_clean_quotation_is_high_confidence_and_proposes_a_new_opportunity(world) -> None:
    world.email(1, [world.file("CN01022-Ana Prueba - Synthon.pdf", _oq("01022-26", "Ana Prueba - Synthon"))])
    review, run = _run(world)
    (v,) = run.documents.values()
    assert v.confidence == qp.CONFIDENCE_HIGH and v.automatable
    assert v.classification == qp.CLS_CUSTOMER_QUOTATION
    assert v.proposed_quote_number == "01022-26"
    assert v.proposed_opportunity == qr.OPPORTUNITY_CREATE_NEW
    assert v.rules == ("P13",) and v.reasons == ()
    (e,) = run.emails
    assert e.automatable and e.proposed_quote_numbers == ("01022-26",)
    assert run.human == []


def test_p02_a_filename_that_contradicts_the_printed_number_goes_to_a_human(world) -> None:
    world.email(1, [world.file("CN180-Ana Prueba.pdf", _oq("01080-26", "Ana Prueba"))])
    _, run = _run(world)
    (v,) = run.documents.values()
    assert v.classification == qp.CLS_NUMBER_UNRESOLVED
    assert v.confidence == qp.CONFIDENCE_LOW
    assert v.proposed_quote_number is None and v.proposed_opportunity == qp.OPPORTUNITY_HUMAN


def _labdelivery_quote(world: World, email_id: int = 1, *, addressee: str = "Ana Prueba - Ceaf",
                       thread: str | None = None) -> None:
    world.email(email_id, [world.file(f"CN011728A-{email_id}.pdf",
                                      _oq("011728A-25", addressee, header=LABDELIVERY))], thread=thread)


def test_p03_labdelivery_sent_by_origenlab_to_a_client_is_origenlab(world) -> None:
    """Ceaf-shaped: a Labdelivery header, sent from our own address to a client."""
    _labdelivery_quote(world)
    _, run = _run(world)
    (v,) = run.documents.values()
    assert v.issuer == qp.ISSUER_LABDELIVERY
    assert v.reasons == () and v.automatable and v.proposed_quote_number == "011728A-25"
    assert "Labdelivery header recognised as OrigenLab's commercial identity (P03)" in v.evidence


def test_p03_labdelivery_from_another_sender_is_not_recognised(world) -> None:
    _labdelivery_quote(world)
    world.records[-1]["payload"]["sender"] = "Otra Persona <otra@proveedor.example.cl>"
    _, run = _run(world)
    (v,) = run.documents.values()
    assert qp.R_ALTERNATE_ISSUER in v.reasons and not v.automatable
    assert any("not sent from an OrigenLab address" in e for e in v.evidence)


def test_p03_labdelivery_is_never_recognised_without_configured_own_senders(world) -> None:
    _labdelivery_quote(world)
    report, _ = world.audit()
    staging = qr.load_staging(world.staging_dir)
    review = dr.build_document_review(staging, report)
    issuers = {c.sha256: qp.ISSUER_LABDELIVERY for c in review.candidates}
    (v,) = qp.dry_run(staging, review, issuers).documents.values()
    assert qp.R_ALTERNATE_ISSUER in v.reasons


def test_p03_labdelivery_in_a_supplier_thread_stays_with_a_human(world) -> None:
    _labdelivery_quote(world, 1, thread="proveedor")
    world.email(2, [world.file("Plano.pdf", BROCHURE)], thread="proveedor", proposed=[])
    _direction(world, 2, qp.DIRECTION_SUPPLIER)
    _, run = _run(world)
    (v,) = run.documents.values()
    assert qp.R_ALTERNATE_ISSUER in v.reasons and not v.automatable
    assert any("supplier correspondence" in e for e in v.evidence)


def test_p03_labdelivery_addressed_to_us_or_unclear_direction_stays_with_a_human(world) -> None:
    _labdelivery_quote(world, 1, addressee="Persona Inventada - Labdelivery")
    _labdelivery_quote(world, 2)
    _direction(world, 2, "ambiguous")
    _, run = _run(world)
    by_email = {v.canonical_email_id: v for v in run.documents.values()}
    assert qp.R_ALTERNATE_ISSUER in by_email[1].reasons
    assert any("addressed to us" in e for e in by_email[1].evidence)
    assert {qp.R_ALTERNATE_ISSUER, qp.R_DIRECTION_UNCLEAR} <= set(by_email[2].reasons)


def test_p03_supplier_quotation_and_supplier_correspondence_go_to_a_human(world) -> None:
    # Certlab-shaped: another issuer quoting OrigenLab's own staff.
    world.email(1, [world.file("1338- PROVEEDOR COTIZACION.pdf",
                               _oq("1338/2026", "Persona Inventada - OrigenLab", header=FOREIGN))], proposed=[])
    world.email(2, [world.file("Plano transductor.pdf", BROCHURE)], proposed=[])
    _direction(world, 2, qp.DIRECTION_SUPPLIER)
    _, run = _run(world)
    (v,) = run.documents.values()
    assert v.issuer == qp.ISSUER_FOREIGN
    assert v.classification == qp.CLS_SUPPLIER_DOCUMENT and v.confidence == qp.CONFIDENCE_LOW
    by_id = {e.email_id: e for e in run.emails}
    assert by_id[2].classification == qp.CLS_SUPPLIER_CORRESPONDENCE and not by_id[2].automatable
    assert {h.key for h in run.human} == {v.sha256, "2"}


def test_p10_unclear_direction_goes_to_a_human(world) -> None:
    world.email(1, [world.file("CN01151-Ana Prueba.pdf", _oq("01151-26", "Ana Prueba"))])
    _direction(world, 1, "ambiguous")
    _, run = _run(world)
    (v,) = run.documents.values()
    assert v.reasons == (qp.R_DIRECTION_UNCLEAR,) and v.confidence == qp.CONFIDENCE_MEDIUM


def test_p07_a_serial_named_by_an_unreadable_cn_file_blocks_automation(world) -> None:
    world.email(1, [world.file("CN01201-Ana Prueba - Corteva.pdf", _oq("01201-26", "Ana Prueba - Corteva"))])
    # Another email carries a file named CN01201 whose text is not readable as a quotation.
    world.email(2, [world.file("CN01201-Otra Persona.xlsx - COTIZACIÓN PDF.pdf", BROCHURE)])
    _, run = _run(world)
    (v,) = run.documents.values()
    assert qp.R_SERIAL_IN_UNREAD_FILE in v.reasons and not v.automatable
    e2 = next(e for e in run.emails if e.email_id == 2)
    assert e2.classification == qp.CLS_UNREADABLE_CN_FILE and e2.confidence == qp.CONFIDENCE_LOW


def test_p11_an_email_with_only_brochures_proposes_nothing(world) -> None:
    world.email(1, [world.file("Catalogo-Ejemplo.pdf", BROCHURE)], proposed=[])
    _, run = _run(world)
    (e,) = run.emails
    assert e.classification == qp.CLS_NO_QUOTATION
    assert e.confidence == qp.CONFIDENCE_HIGH and e.proposed_opportunity == qp.OPPORTUNITY_NONE
    assert e.proposed_quote_numbers == () and run.documents == {}


def test_no_inference_from_similar_names(world) -> None:
    """'Universidad Autónoma' and 'Universidad Autónoma de Chile' are different printed keys:
    neither is joined to the other, so both stay high confidence on their own."""
    world.email(1, [world.file("CN01190-a.pdf", _oq("01190-26", "Juan Prueba – Universidad Autónoma"))])
    world.email(2, [world.file("CN01191-b.pdf", _oq("01191-26", "Ana Prueba – Universidad Autónoma de Chile"))])
    _, run = _run(world)
    assert all(v.automatable for v in run.documents.values())
    assert all(v.related_documents == () for v in run.documents.values())


def test_the_policy_is_computed_without_the_ledgers(world) -> None:
    world.email(1, [world.file("CN01022-a.pdf", _oq("01022-26", "Ana Prueba - Synthon"))])
    review, bare = _run(world)
    sha = next(iter(bare.documents))
    _, decided = _run(world, doc_ledger=[_doc_decision(sha, 1, "01022-26", decision=qr.DECISION_REJECT)])
    assert decided.documents == bare.documents


# --- regressions: the audited decisions -----------------------------------------------


def test_regression_bioeq_resend_in_the_same_thread_is_one_quotation(world) -> None:
    leaflet = world.file("Leaflet-Ejemplo.PDF", BROCHURE)
    quote = world.file("CN01005-Bioeq SpA.pdf", _oq("1005-26", "Bioeq SpA"))
    world.email(1, [quote, leaflet], thread="bioeq")
    world.email(2, [quote, leaflet], thread="bioeq")
    review, run = _run(world, email_ledger=[
        _email_decision(1, qr.DECISION_CONFIRM, "CN01005", "create_new"),
        _email_decision(2, qr.DECISION_PENDING),
    ])
    (v,) = run.documents.values()
    assert v.automatable and v.canonical_email_id == 1 and v.proposed_quote_number == "1005-26"
    by_id = {e.email_id: e for e in run.emails}
    assert by_id[1].classification == qp.CLS_CUSTOMER_QUOTATION
    assert by_id[2].classification == qp.CLS_DUPLICATE_OCCURRENCE and "P01" in by_id[2].rules
    assert by_id[2].proposed_opportunity.startswith("attach to document")
    # The reconciled email confirmation and both email decisions agree with the policy.
    assert _comparison(run, v.sha256).outcome == qp.AGREE_AUTOMATABLE
    assert _comparison(run, v.sha256).human_source == "email_reconciliation"
    assert _comparison(run, "1").outcome == qp.AGREE_AUTOMATABLE
    assert _comparison(run, "2").outcome == qp.AGREE_AUTOMATABLE


def test_regression_instafarm_bounced_resends_are_one_document(world) -> None:
    quote = world.file("Cotización 1006- Ana Prueba - InstaFarm.pdf", _oq("1006-26", "Ana Prueba - InstaFarm"))
    for n in (1, 2, 3):
        world.email(n, [quote], thread="insta", proposed=[])
    review, run = _run(world)
    (v,) = run.documents.values()
    assert v.email_ids == (1, 2, 3) and v.canonical_email_id == 1
    assert v.automatable  # identical bytes alone never send a document to a human
    assert [e.classification for e in run.emails] == [
        qp.CLS_CUSTOMER_QUOTATION, qp.CLS_DUPLICATE_OCCURRENCE, qp.CLS_DUPLICATE_OCCURRENCE]


def test_regression_instafarm_a_later_quote_in_the_thread_needs_a_human(world) -> None:
    quote = world.file("Cotización 1006- Ana Prueba - InstaFarm.pdf", _oq("1006-26", "Ana Prueba - InstaFarm"))
    world.email(1, [quote], thread="insta", proposed=[])
    world.email(2, [quote], thread="insta", proposed=[])
    world.email(3, [world.file("CN01023-Ana Prueba - InstaFarm.pdf", _oq("01023-26", "Ana Prueba - InstaFarm"))],
                thread="insta")
    review, run0 = _run(world)
    sha = _sha_of(review, "1006-26")
    _, run = _run(world, doc_ledger=[_doc_decision(sha, 1, "1006-26")])
    assert run.documents[sha].reasons == (qp.R_SEVERAL_IN_THREAD,)
    assert run.documents[sha].confidence == qp.CONFIDENCE_MEDIUM
    assert _comparison(run, sha).outcome == qp.POLICY_STRICTER
    # The decided document leaves the human list; the later quote stays on it.
    assert {h.key for h in run.human} == {_sha_of(review, "01023-26")}


def test_regression_eurofarma_two_quotations_in_one_email_stay_with_a_human(world) -> None:
    a = world.file("Cotización 1007- Ana Prueba - Eurofarma.pdf", _oq("1007-26", "Ana Prueba - Eurofarma"))
    b = world.file("CN1010-Ana Prueba - Eurofarma.pdf", _oq("1010-26", "Ana Prueba - Eurofarma"))
    world.email(1, [a, world.file("Leaflet-Ejemplo.PDF", BROCHURE), b], proposed=[])
    review, run = _run(world, doc_ledger=[
        _doc_decision(a[1], 1, "1007-26", planned="00000000-0000-4000-8000-00000000e001"),
        _doc_decision(b[1], 1, "1010-26", mode="planned", planned="00000000-0000-4000-8000-00000000e001"),
    ])
    for sha in (a[1], b[1]):
        v = run.documents[sha]
        assert v.classification == qp.CLS_SEVERAL and not v.automatable
        assert qp.R_SEVERAL_IN_EMAIL in v.reasons
        assert _comparison(run, sha).outcome == qp.POLICY_STRICTER
    (e,) = run.emails
    assert e.classification == qp.CLS_SEVERAL_IN_EMAIL and e.proposed_opportunity == qp.OPPORTUNITY_HUMAN
    assert run.human == []  # both documents decided by the owner


def test_regression_golden_omega_thread_and_separate_request(world) -> None:
    rut = "76.000.001-1"
    world.email(1, [world.file("CN01112-a.pdf", _oq("01112-26", "Golden Omega S.A.", rut=rut))], thread="go")
    world.email(2, [world.file("CN01118-a.pdf", _oq("01118-26", "Golden Omega S.A.", rut=rut))], thread="go")
    world.email(3, [world.file("CN01150-a.pdf", _oq("01150-26", "Golden Omega S.A.", rut=rut))], thread="go2")
    review, run = _run(world)
    first, second, other = (run.documents[_sha_of(review, n)] for n in ("01112-26", "01118-26", "01150-26"))
    for v in (first, second):
        assert qp.R_SEVERAL_IN_THREAD in v.reasons and not v.automatable
    # Same company and RUT in another thread: a human decides whether it is a new opportunity.
    assert other.reasons == (qp.R_SAME_CLIENT_OTHER_THREAD,)
    assert other.classification == qp.CLS_NEEDS_REVIEW and other.confidence == qp.CONFIDENCE_MEDIUM


def test_regression_virbac_number_shared_with_another_client_and_a_later_version(world) -> None:
    world.email(1, [world.file("CN1046- Otro Cliente - Universidad Ejemplo.pdf",
                               _oq("01046-26", "Otro Cliente - Universidad Ejemplo"))], thread="pr")
    world.email(2, [world.file("CN01046-Ana Prueba - Virbac.pdf", _oq("01046-26", "Ana Prueba - Virbac"))],
                thread="vb")
    world.email(3, [world.file("CN01156-Centro Ejemplo Ltda.pdf",
                               _oq("01156-26", "Centro Ejemplo Ltda.", rut="86.000.002-2"))], thread="vb")
    review, run = _run(world)
    virbac = next(v for v in run.documents.values() if "At. Ana Prueba - Virbac" in v.client_lines)
    assert virbac.classification == qp.CLS_CLIENT_CONFLICT and virbac.confidence == qp.CONFIDENCE_LOW
    assert qp.R_SEVERAL_IN_THREAD in virbac.reasons
    assert not run.documents[_sha_of(review, "01156-26")].automatable


def test_regression_universidad_adventista_conflict_and_revision(world) -> None:
    world.email(1, [world.file("CN1065-a.pdf", _oq("01065-26", "Dra. Ana Prueba – Universidad Adventista de Chile"))],
                thread="ua")
    world.email(2, [world.file("CN01065-b.pdf", _oq("01065-26", "Juan Prueba – Universidad de Valparaiso"))],
                thread="uv")
    world.email(3, [world.file("CN1065A-a.pdf", _oq("01065A-26", "Dra. Ana Prueba – Universidad Adventista de Chile"))],
                thread="ua")
    review, _ = _run(world)
    adventista = next(c.sha256 for c in review.candidates if c.printed_quote_numbers == ("01065-26",)
                      and "Adventista" in c.client_evidence_lines()[0])
    _, run = _run(world, doc_ledger=[_doc_decision(adventista, 1, "01065-26")])
    v = run.documents[adventista]
    assert v.classification == qp.CLS_CLIENT_CONFLICT
    assert {qp.R_CLIENT_CONFLICT, qp.R_VERSION_CHANGE, qp.R_SEVERAL_IN_THREAD} <= set(v.reasons)
    assert _comparison(run, adventista).outcome == qp.POLICY_STRICTER
    revision = run.documents[_sha_of(review, "01065A-26")]
    # The revision shares serial 1065 with Adventista's version and with Valparaíso's quote.
    assert {qp.R_VERSION_CHANGE, qp.R_CLIENT_CONFLICT} <= set(revision.reasons)
    assert not revision.automatable


def test_regression_als_patagonia_catalogues_beside_one_quotation(world) -> None:
    world.email(1, [world.file("Catalogo-centrifugas.pdf", BROCHURE)], thread="als", proposed=[])
    world.email(2, [world.file("Catalogo-serie-22.pdf", BROCHURE + ["serie 22"])], thread="als", proposed=[])
    world.email(3, [world.file("CN01062-Ana Prueba – ALS Patagonia S.A.pdf",
                               _oq("01062-26", "Ana Prueba – ALS Patagonia S.A"))], thread="als")
    review, run = _run(world)
    sha = _sha_of(review, "01062-26")
    _, run = _run(world, doc_ledger=[_doc_decision(sha, 3, "01062-26")])
    assert run.documents[sha].automatable
    assert _comparison(run, sha).outcome == qp.AGREE_AUTOMATABLE
    assert [e.classification for e in run.emails] == [qp.CLS_NO_QUOTATION, qp.CLS_NO_QUOTATION,
                                                       qp.CLS_CUSTOMER_QUOTATION]


def test_regression_generic_address_client_stays_pending(world) -> None:
    """The ONGO case: a real quotation addressed only to a generic mailbox."""
    world.email(1, [world.file("CN1051-ONGO-UP400ST.pdf", _oq("01051-26", "hola@ongo.example.cl")),
                    world.file("Ficha-Ejemplo.pdf", BROCHURE)])
    review, run = _run(world, email_ledger=[_email_decision(1, qr.DECISION_PENDING)])
    (v,) = run.documents.values()
    assert v.classification == qp.CLS_GENERIC_CLIENT and v.confidence == qp.CONFIDENCE_LOW
    assert _comparison(run, "1").outcome == qp.POLICY_STRICTER
    assert [h.key for h in run.human] == [v.sha256]


def test_regression_client_change_between_versions_is_a_conflict(world) -> None:
    """U. del Alba / PUC: one number, the client corrected between two versions."""
    old = world.file("CN011415A-Ana Prueba – Pontificia Universidad Católica de Chile.pdf",
                     _oq("011415A-26", "Ana Prueba – Pontificia Universidad Católica de Chile"))
    new = world.file("CN011415A-Ana Prueba – Universidad del Alba.pdf",
                     _oq("011415A-26", "Ana Prueba – Universidad del Alba"))
    world.email(1, [old], thread="alba")
    world.email(2, [new], thread="alba")
    _, run = _run(world, email_ledger=[_email_decision(1, qr.DECISION_REJECT)],
                  doc_ledger=[_doc_decision(new[1], 2, "011415A-26")])
    for sha in (old[1], new[1]):
        assert run.documents[sha].classification == qp.CLS_CLIENT_CONFLICT
        assert run.documents[sha].confidence == qp.CONFIDENCE_LOW
    assert _comparison(run, new[1]).outcome == qp.POLICY_STRICTER
    assert _comparison(run, "1").outcome == qp.POLICY_STRICTER


def test_regression_same_number_same_client_is_a_version_change(world) -> None:
    """Ceaf / Universidad Autónoma / MMoll: same client, same printed number, other bytes."""
    world.email(1, [world.file("CN011728A-a.pdf", _oq("011728A-25", "Ana Prueba - Ceaf"))], thread="ceaf")
    world.email(2, [world.file("CN011728A-b.pdf", _oq("011728A-26", "Ana Prueba - Ceaf", model="Balanza modelo Y"))],
                thread="ceaf")
    _, run = _run(world)
    for v in run.documents.values():
        assert v.classification == qp.CLS_VERSION_CHANGE and qp.R_VERSION_CHANGE in v.reasons
        assert not v.automatable


def test_regression_document_without_client_block_needs_the_thread(world) -> None:
    """Universidad de Concepción 01042-26: the PDF names nobody; only a human reading the
    thread could confirm it."""
    lines = [line for line in _oq("01042-26", "x") if not line.startswith("At.")]
    world.email(1, [world.file("CN1042-26-UP400St.pdf", lines)])
    review, run = _run(world)
    (v,) = run.documents.values()
    assert v.classification == qp.CLS_NO_CLIENT and v.confidence == qp.CONFIDENCE_LOW


def test_comparison_reports_every_kind_of_disagreement(world) -> None:
    for n, number in ((1, "01201-26"), (2, "01202-26"), (3, "01203-26")):
        world.email(n, [world.file(f"CN{number[:5]}-x{n}.pdf", _oq(number, f"Cliente {n} SpA"))])
    review, _ = _run(world)
    s1, s2, s3 = (_sha_of(review, n) for n in ("01201-26", "01202-26", "01203-26"))
    _, run = _run(world, doc_ledger=[
        _doc_decision(s1, 1, "01299-26"),
        _doc_decision(s2, 2, "01202-26", mode="existing"),
        _doc_decision(s3, 3, None, decision=qr.DECISION_REJECT),
    ])
    assert _comparison(run, s1).outcome == qp.DISAGREE_NUMBER
    assert _comparison(run, s2).outcome == qp.DISAGREE_OPPORTUNITY
    assert _comparison(run, s3).outcome == qp.DISAGREE_STATUS


# --- no writes ------------------------------------------------------------------------


def test_module_imports_no_database_driver_and_opens_no_file() -> None:
    tree = ast.parse(_MODULE.read_text(encoding="utf-8"))
    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported |= {a.name for a in node.names}
        elif isinstance(node, ast.ImportFrom):
            imported.add(node.module or "")
    forbidden = ("psycopg", "sqlite3", "sqlalchemy", "origenlab_api.v2.repository",
                 "origenlab_api.v2.command", "googleapiclient", "requests", "httpx", "urllib",
                 "subprocess", "os", "pathlib")
    assert not [m for m in imported if m.startswith(forbidden)], imported
    calls = {getattr(n.func, "attr", getattr(n.func, "id", None)) for n in ast.walk(tree) if isinstance(n, ast.Call)}
    assert not calls & {"open", "write_text", "write_bytes", "unlink", "mkdir"}
    assert not [n for n in ast.walk(tree) if isinstance(n, ast.Call)
                and isinstance(n.func, ast.Attribute) and n.func.attr == "append"
                and "ledger" in ast.unparse(n.func.value)]


def _load_script():
    spec = importlib.util.spec_from_file_location("quote_review_policy_dryrun", _SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def test_dry_run_script_writes_only_its_report_and_leaves_the_ledgers_untouched(world, tmp_path) -> None:
    quote = world.file("CN01005-Bioeq SpA.pdf", _oq("1005-26", "Bioeq SpA"))
    world.email(1, [quote])
    world.email(2, [world.file("CN1051-x.pdf", _oq("01051-26", "hola@ongo.example.cl"))])
    report, _ = world.audit()
    identity = tmp_path / "identity"
    (identity / "texts").mkdir(parents=True)
    (identity / "quote_document_identity.json").write_text(json.dumps(report), encoding="utf-8")
    for d in report["documents"]:
        text = qd.extract_text(world.docs_dir / f"{d['sha256']}.pdf").text
        (identity / "texts" / f"{d['sha256']}.txt").write_text(text, encoding="utf-8")
    ledger = tmp_path / "review" / "decisions.jsonl"
    ledger.parent.mkdir()
    ledger.write_text(json.dumps(_email_decision(2, qr.DECISION_PENDING)) + "\n", encoding="utf-8")
    doc_ledger = ledger.with_name(dr.DOCUMENT_LEDGER_FILE)
    doc_ledger.write_text(json.dumps(_doc_decision(quote[1], 1, "1005-26")) + "\n", encoding="utf-8")
    hashes = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in (ledger, doc_ledger)}

    out = tmp_path / "out"
    mod = _load_script()
    argv = ["--staging-dir", str(world.staging_dir), "--identity-dir", str(identity),
            "--ledger", str(ledger), "--out", str(out)]
    assert mod.main(argv) == 0
    assert {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in hashes} == hashes
    assert sorted(p.name for p in out.iterdir()) == [
        "documents.csv", "emails.csv", "human_intervention.csv", "ledger_diff.csv",
        "policy_spec.json", "report.md", "summary.json"]
    emails = (out / "emails.csv").read_text(encoding="utf-8").splitlines()
    assert emails[0].startswith("email_id,cola,direccion,asunto,documentos_cotizacion,clasificacion_propuesta,"
                                "oportunidad_propuesta,nivel_de_confianza,automatizable")
    assert len(emails) == 3
    summary = json.loads((out / "summary.json").read_text(encoding="utf-8"))
    assert summary["inputs_sha256"] == summary["inputs_sha256_after"]
    assert summary["documents_by_confidence"] == {"high": 1, "low": 1}
    # A second run refuses to overwrite the report.
    assert mod.main(argv) == 2
