"""The high-confidence application report: the frozen policy and the safe/suggestion split.

PDFs are generated by the policy suite's `World` with invented text. Nothing comes from the
real staging.
"""

from __future__ import annotations

import dataclasses
import hashlib
import importlib.util
import json
import sys
from pathlib import Path

import pytest
from test_v2_quote_review_policy import (
    LABDELIVERY,
    _doc_decision,
    _oq,
    _run,
    _sha_of,
)
from test_v2_quote_review_policy import world as world  # noqa: F401  (fixture)

from origenlab_api.v2 import quote_apply_candidates as qa
from origenlab_api.v2 import quote_document_identity as qd
from origenlab_api.v2 import quote_document_review as dr
from origenlab_api.v2 import quote_evidence_review as qr
from origenlab_api.v2 import quote_review_policy as qp
from origenlab_api.v2.quote_confirmation_reconciliation import effective_document_states

_SCRIPTS = Path(__file__).resolve().parents[1] / "scripts"
_SCRIPT = _SCRIPTS / "quote_high_confidence_apply_report.py"


def _states(world, review, doc_ledger: list[dict]):
    path = world.root / "review" / dr.DOCUMENT_LEDGER_FILE
    path.write_text("".join(json.dumps(r) + "\n" for r in doc_ledger), encoding="utf-8")
    return effective_document_states(review, dr.DocumentDecisionLedger(path), {})


def _only(cands: list[qa.ApplyCandidate]) -> qa.ApplyCandidate:
    (a,) = cands
    return a


# --- the freeze -----------------------------------------------------------------------


def test_the_policy_is_frozen_at_the_owner_accepted_version() -> None:
    assert qp.policy_fingerprint() == qp.FROZEN_POLICY_SHA256
    assert qp.assert_policy_frozen() == qp.FROZEN_POLICY_SHA256


@pytest.mark.parametrize("field", ["id", "title", "outcome", "precedent"])
def test_changing_any_rule_text_breaks_the_freeze(field: str) -> None:
    changed = list(qp.POLICY)
    changed[2] = dataclasses.replace(changed[2], **{field: getattr(changed[2], field) + "."})
    with pytest.raises(qp.PolicyChanged):
        qp.assert_policy_frozen(changed)
    with pytest.raises(qp.PolicyChanged):
        qp.assert_policy_frozen(qp.POLICY[:-1])


# --- the split ------------------------------------------------------------------------


def test_a_clean_undecided_quotation_is_a_safe_confirmation(world) -> None:
    world.email(1, [world.file("CN01022-Ana Prueba - Synthon.pdf", _oq("01022-26", "Ana Prueba - Synthon"))])
    review, run = _run(world)
    a = _only(qa.build_apply_candidates(run, review, {}))
    assert (a.separation, a.action, a.ledger_state) == (qa.SEPARATION_SAFE, qa.ACTION_CONFIRM, qa.LEDGER_UNDECIDED)
    assert a.printed_number == "01022-26" and a.number_key == "1022-26" and a.serial == 1022
    assert a.organization == "Synthon" and a.contact == "Ana Prueba"
    assert a.rules == ("P13",) and a.suggestion_reasons == ()
    assert a.safe_fields == ("clasificacion=customer_quotation", "numero=01022-26", "correo_canonico=1")
    # The opportunity and the CRM link are the operator's, even for a safe document.
    assert a.suggestion_fields[0] == "oportunidad=nueva (create_new) propuesta"
    assert "organizacion_crm=Synthon" in a.suggestion_fields
    assert not any(f.startswith("cotizacion=") for f in a.suggestion_fields)
    assert qa.max_printed_serial(review, {a.sha256: qp.ISSUER_ORIGENLAB}) == 1022


def test_a_client_block_without_a_split_is_left_to_the_operator(world) -> None:
    world.email(1, [world.file("CN01191-ICN Prueba.pdf", _oq("01191-26", "ICN Prueba"))])
    review, run = _run(world)
    a = _only(qa.build_apply_candidates(run, review, {}))
    assert a.organization is None
    assert "el bloque de cliente no separa persona de organización" in a.notes
    assert "cliente_crm=ICN Prueba (persona u organización: lo decide el operador)" in a.suggestion_fields


def test_a_serial_at_or_beyond_the_approved_seed_is_only_a_suggestion(world) -> None:
    world.email(1, [world.file("CN01235-Ana Prueba - Nogal.pdf", _oq("01235-26", "Ana Prueba - Nogal"))])
    world.email(2, [world.file("CN01234-Luis Prueba - Arauco.pdf", _oq("01234-26", "Luis Prueba - Arauco"))])
    review, run = _run(world)
    by_number = {a.printed_number: a for a in qa.build_apply_candidates(run, review, {})}
    at_seed, below = by_number["01235-26"], by_number["01234-26"]
    assert at_seed.separation == qa.SEPARATION_SUGGESTION and at_seed.action == qa.ACTION_OPERATOR
    assert at_seed.suggestion_reasons == (qa.S_AT_OR_BEYOND_SEED,)
    assert at_seed.safe_fields == ()
    assert at_seed.suggestion_fields[0] == "cotizacion=customer_quotation 01235-26"
    assert below.separation == qa.SEPARATION_SAFE


def test_a_reserved_serial_is_only_a_suggestion(world) -> None:
    world.email(1, [world.file("CN01500-Ana Prueba - Nogal.pdf", _oq("01500-26", "Ana Prueba - Nogal"))])
    review, run = _run(world)
    a = _only(qa.build_apply_candidates(run, review, {}, seed_next_serial=9999))
    assert a.suggestion_reasons == (qa.S_RESERVED_SERIAL,)


def test_a_recognised_labdelivery_quotation_is_only_a_suggestion(world) -> None:
    world.email(1, [world.file("CN0980-Ana Prueba - Ceaf.pdf", _oq("0980-26", "Ana Prueba - Ceaf", header=LABDELIVERY))])
    review, run = _run(world)
    a = _only(qa.build_apply_candidates(run, review, {}))
    assert a.issuer == qp.ISSUER_LABDELIVERY
    assert a.suggestion_reasons == (qa.S_LABDELIVERY_SERIES,)
    assert a.rules == ("P03", "P13")


def test_an_owner_confirmation_that_agrees_needs_nothing_applied(world) -> None:
    world.email(1, [world.file("CN01022-Ana Prueba - Synthon.pdf", _oq("01022-26", "Ana Prueba - Synthon"))])
    review, run = _run(world)
    sha = _sha_of(review, "01022-26")
    states = _states(world, review, [_doc_decision(sha, 1, "1022-26")])
    a = _only(qa.build_apply_candidates(run, review, states))
    assert (a.separation, a.action, a.ledger_state) == (
        qa.SEPARATION_SAFE, qa.ACTION_NONE_ALREADY_CONFIRMED, qa.LEDGER_CONFIRMED_AGREES)
    assert a.planned_opportunity_id == "00000000-0000-4000-8000-000000000001"
    assert "el ledger guarda 1022-26; el PDF imprime 01022-26 (mismo número)" in a.notes


def test_an_owner_decision_that_differs_is_never_overridden(world) -> None:
    world.email(1, [world.file("CN01022-Ana Prueba - Synthon.pdf", _oq("01022-26", "Ana Prueba - Synthon"))])
    review, run = _run(world)
    sha = _sha_of(review, "01022-26")
    for row in ([_doc_decision(sha, 1, None, decision=qr.DECISION_REJECT)],
                [_doc_decision(sha, 1, "1023-26")]):
        a = _only(qa.build_apply_candidates(run, review, _states(world, review, row)))
        assert a.ledger_state == qa.LEDGER_DIFFERS
        assert a.suggestion_reasons == (qa.S_LEDGER_DIFFERS,) and a.safe_fields == ()


def test_documents_below_high_confidence_are_not_candidates_and_stay_held(world) -> None:
    world.email(1, [world.file("CN01022-Ana Prueba - Synthon.pdf", _oq("01022-26", "Ana Prueba - Synthon"))])
    world.email(2, [world.file("CN1051-x.pdf", _oq("01051-26", "hola@ongo.example.cl"))])
    review, run = _run(world)
    cands = qa.build_apply_candidates(run, review, {})
    assert [a.printed_number for a in cands] == ["01022-26"]
    held = qa.held_for_human(run, cands)
    assert [(h.target, h.classification) for h in held] == [("document", qp.CLS_GENERIC_CLIENT)]


def test_held_for_human_refuses_an_overlap(world) -> None:
    world.email(1, [world.file("CN01022-Ana Prueba - Synthon.pdf", _oq("01022-26", "Ana Prueba - Synthon"))])
    review, run = _run(world)
    (a,) = qa.build_apply_candidates(run, review, {})
    run.human.append(qp.HumanCase("document", a.sha256, (1,), "x", qp.CONFIDENCE_LOW, (), (), ()))
    with pytest.raises(ValueError):
        qa.held_for_human(run, [a])


def test_the_module_opens_no_file_and_imports_no_driver() -> None:
    import ast
    tree = ast.parse(Path(qa.__file__).read_text(encoding="utf-8"))
    imported = {a.name for n in ast.walk(tree) if isinstance(n, ast.Import) for a in n.names}
    imported |= {n.module or "" for n in ast.walk(tree) if isinstance(n, ast.ImportFrom)}
    forbidden = ("psycopg", "sqlite3", "sqlalchemy", "googleapiclient", "requests", "httpx", "urllib",
                 "subprocess", "os", "pathlib", "origenlab_api.v2.repository", "origenlab_api.v2.command")
    assert not [m for m in imported if m.startswith(forbidden)], imported
    calls = {getattr(n.func, "attr", getattr(n.func, "id", None)) for n in ast.walk(tree) if isinstance(n, ast.Call)}
    assert not calls & {"open", "write_text", "write_bytes", "unlink", "mkdir"}


# --- the script -----------------------------------------------------------------------


def _load_script():
    sys.path.insert(0, str(_SCRIPTS))
    try:
        spec = importlib.util.spec_from_file_location("quote_high_confidence_apply_report", _SCRIPT)
        mod = importlib.util.module_from_spec(spec)
        assert spec.loader is not None
        spec.loader.exec_module(mod)
        return mod
    finally:
        sys.path.remove(str(_SCRIPTS))


def test_the_script_writes_only_its_report_and_leaves_the_ledgers_untouched(world, tmp_path) -> None:
    quote = world.file("CN01005-Bioeq SpA.pdf", _oq("1005-26", "Bioeq SpA"))
    world.email(1, [quote])
    world.email(2, [world.file("CN01236-Ana Prueba - Nogal.pdf", _oq("01236-26", "Ana Prueba - Nogal"))])
    world.email(3, [world.file("CN1051-x.pdf", _oq("01051-26", "hola@ongo.example.cl"))])
    report, _ = world.audit()
    identity = tmp_path / "identity"
    (identity / "texts").mkdir(parents=True)
    (identity / "quote_document_identity.json").write_text(json.dumps(report), encoding="utf-8")
    for d in report["documents"]:
        text = qd.extract_text(world.docs_dir / f"{d['sha256']}.pdf").text
        (identity / "texts" / f"{d['sha256']}.txt").write_text(text, encoding="utf-8")
    ledger = tmp_path / "review" / "decisions.jsonl"
    ledger.parent.mkdir()
    ledger.write_text("", encoding="utf-8")
    doc_ledger = ledger.with_name(dr.DOCUMENT_LEDGER_FILE)
    doc_ledger.write_text(json.dumps(_doc_decision(quote[1], 1, "1005-26")) + "\n", encoding="utf-8")
    hashes = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in (ledger, doc_ledger)}

    mod = _load_script()
    out = tmp_path / "out"
    argv = ["--staging-dir", str(world.staging_dir), "--identity-dir", str(identity), "--ledger", str(ledger),
            "--compare-dryrun", str(tmp_path / "no-dryrun"), "--out", str(out)]
    assert mod.main(argv) == 0
    assert {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in hashes} == hashes
    assert sorted(p.name for p in out.iterdir()) == [
        "high_confidence_apply_candidates.csv", "high_confidence_review.md", "human_review_hold.csv",
        "policy_freeze.json", "summary.json"]
    summary = json.loads((out / "summary.json").read_text(encoding="utf-8"))
    assert summary["applied"] is False
    assert summary["by_action"] == {qa.ACTION_NONE_ALREADY_CONFIRMED: 1, qa.ACTION_OPERATOR: 1}
    assert summary["human_review_hold"] == 1
    freeze = json.loads((out / "policy_freeze.json").read_text(encoding="utf-8"))
    assert freeze["policy_fingerprint_sha256"] == qp.FROZEN_POLICY_SHA256
    assert freeze["inputs_sha256"] == freeze["inputs_sha256_after"]
    md = (out / "high_confidence_review.md").read_text(encoding="utf-8")
    assert "## Confirmación segura (1)" in md and "## Solo sugerencia para el operador (1)" in md
    assert mod.main(argv) == 2  # never overwrites

    # A dry run whose high-confidence set differs stops the report before anything is written.
    dryrun = tmp_path / "dryrun"
    dryrun.mkdir()
    (dryrun / "documents.csv").write_text("sha256,nivel_de_confianza\nabc,alta\n", encoding="utf-8")
    other = tmp_path / "out2"
    assert mod.main([*argv[:-4], "--compare-dryrun", str(dryrun), "--out", str(other)]) == 4
    assert not other.exists()


def _script_inputs(world, tmp_path):
    world.email(1, [world.file("CN01236-Ana Prueba - Nogal.pdf", _oq("01236-26", "Ana Prueba - Nogal"))])
    report, _ = world.audit()
    identity = tmp_path / "identity"
    (identity / "texts").mkdir(parents=True)
    (identity / "quote_document_identity.json").write_text(json.dumps(report), encoding="utf-8")
    for d in report["documents"]:
        text = qd.extract_text(world.docs_dir / f"{d['sha256']}.pdf").text
        (identity / "texts" / f"{d['sha256']}.txt").write_text(text, encoding="utf-8")
    ledger = tmp_path / "review" / "decisions.jsonl"
    ledger.parent.mkdir()
    ledger.write_text("", encoding="utf-8")
    ledger.with_name(dr.DOCUMENT_LEDGER_FILE).write_text("", encoding="utf-8")
    return ["--staging-dir", str(world.staging_dir), "--identity-dir", str(identity), "--ledger", str(ledger),
            "--compare-dryrun", str(tmp_path / "no-dryrun")]


def test_a_proposed_seed_must_clear_every_printed_serial(world, tmp_path) -> None:
    mod = _load_script()
    base = _script_inputs(world, tmp_path)
    audit = tmp_path / "seed-audit"
    audit.mkdir()
    (audit / "resumen.json").write_text(json.dumps({"max_current_series_serial": 1242}), encoding="utf-8")

    # Not above the staged 01236-26, reserved, or not above what the audit found beyond the staging.
    for extra, out in ((["--seed-next-serial", "1236"], "o1"), (["--seed-next-serial", "1500"], "o2"),
                       (["--seed-next-serial", "1242", "--seed-audit", str(audit)], "o3")):
        assert mod.main([*base, *extra, "--out", str(tmp_path / out)]) == 6
        assert not (tmp_path / out).exists()

    out = tmp_path / "ok"
    assert mod.main([*base, "--seed-next-serial", "1243", "--seed-audit", str(audit), "--out", str(out)]) == 0
    summary = json.loads((out / "summary.json").read_text(encoding="utf-8"))
    assert summary["seed"]["next_serial"] == 1243 and summary["seed"]["status"] == "propuesta, sin aprobar"
    assert summary["seed"]["audit_max_current_series"] == 1242
    assert summary["by_separation"] == {qa.SEPARATION_SAFE: 1}  # 01236-26 is below the proposed seed
    freeze = json.loads((out / "policy_freeze.json").read_text(encoding="utf-8"))
    assert (freeze["approved_seed_next_serial"], freeze["seed_next_serial_used"]) == (1235, 1243)
    assert "semilla **1243** (propuesta, sin aprobar)" in (out / "high_confidence_review.md").read_text(encoding="utf-8")


def test_the_approved_seed_is_reported_even_when_stale(world, tmp_path) -> None:
    mod = _load_script()
    out = tmp_path / "out"
    assert mod.main([*_script_inputs(world, tmp_path), "--out", str(out)]) == 0
    summary = json.loads((out / "summary.json").read_text(encoding="utf-8"))
    assert summary["seed"]["status"] == "aprobada" and summary["by_separation"] == {qa.SEPARATION_SUGGESTION: 1}
    md = (out / "high_confidence_review.md").read_text(encoding="utf-8")
    assert "correlativo ≥ 1235, la semilla aprobada" in md and "Semilla de numeración desactualizada" in md
