"""Email-level confirmations reconciled onto their canonical document, and read-only Drive evidence.

Every PDF is generated by the test with invented text (`example.cl`, made-up people and
numbers), through the identity suite's `World`. Nothing comes from the real staging, Gmail
or Drive.
"""

from __future__ import annotations

import ast
import hashlib
import json
import threading
import uuid
from http.server import ThreadingHTTPServer
from pathlib import Path

import pytest
from test_v2_quote_document_identity import BROCHURE, World, _quote
from test_v2_quote_document_review import _load_script, _req

from origenlab_api.v2 import quote_confirmation_reconciliation as rc
from origenlab_api.v2 import quote_document_review as dr
from origenlab_api.v2 import quote_drive_evidence as de
from origenlab_api.v2 import quote_evidence_review as qr

_API_ROOT = Path(__file__).resolve().parents[1]
_DRIVE_MODULE = _API_ROOT / "src/origenlab_api/v2/quote_drive_evidence.py"
_RECONCILE_MODULE = _API_ROOT / "src/origenlab_api/v2/quote_confirmation_reconciliation.py"
OPERATOR = "op@example.cl"
DRIVE_ID = "1AbCdEfGhIjKlMnOpQrStUvWxYz012345"
FETCHED_AT = "2026-09-24T20:00:00+00:00"


@pytest.fixture
def world(tmp_path: Path) -> World:
    return World(tmp_path)


def _quote_with_duplicate(world: World) -> tuple[str, str]:
    """The 706492/706499 shape: one quotation plus a brochure, resent in the same thread."""
    quote = world.file("CN01005-Cliente Ejemplo SpA.pdf", _quote("1005-26", "Cliente Ejemplo SpA"))
    brochure = world.file("Leaflet-Ejemplo.PDF", BROCHURE)
    world.email(1, [quote, brochure], thread="t-quote")
    world.email(2, [quote, brochure], thread="t-quote")
    return quote[1], brochure[1]


def _two_quote_email(world: World) -> tuple[str, str]:
    a = world.file("Cotización 1007- Ana Prueba - Eurofarma.pdf", _quote("1007-26", "Ana Prueba - Eurofarma"))
    b = world.file("CN1010-Ana Prueba - Eurofarma.pdf", _quote("1010-26", "Ana Prueba - Eurofarma"))
    world.email(1, [a, world.file("Leaflet-Ejemplo.PDF", BROCHURE), b])
    return a[1], b[1]


def _build(world: World) -> tuple[qr.Staging, dr.DocumentReview]:
    report, _ = world.audit()
    staging = qr.load_staging(world.staging_dir)
    return staging, dr.build_document_review(staging, report)


def _ledgers(tmp_path: Path) -> tuple[qr.DecisionLedger, dr.DocumentDecisionLedger]:
    ledger = qr.DecisionLedger(tmp_path / "review" / "decisions.jsonl")
    return ledger, dr.DocumentDecisionLedger(ledger.path.with_name(dr.DOCUMENT_LEDGER_FILE))


def _historical_email_confirm(staging, ledger, email_id, number, **kw) -> dict:
    """An email-level confirmation recorded before this policy existed (as 706492 was)."""
    kw.setdefault("opportunity_mode", qr.OPPORTUNITY_CREATE_NEW)
    entry = qr.build_decision(
        staging.item(email_id), decision=qr.DECISION_CONFIRM, operator=OPERATOR,
        quote_number=number, quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL, **kw,
    )
    ledger.append(entry)
    return entry


def _bytes(*paths: Path) -> dict[str, bytes | None]:
    return {str(p): (p.read_bytes() if p.exists() else None) for p in paths}


def _tree(root: Path) -> dict[str, bytes]:
    return {str(p): p.read_bytes() for p in sorted(root.rglob("*")) if p.is_file()}


# --- one email, one quotation document ----------------------------------------------------


def test_one_email_with_one_quote_document_reconciles(world, tmp_path) -> None:
    quote, brochure = _quote_with_duplicate(world)
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)

    assert review.quote_document_count(1) == 1  # the brochure is not a quotation
    assert rc.email_confirmation_refusal(review, 1, "CN01005") is None
    entry = rc.record_email_decision(
        staging, ledger, review, 1, decision=qr.DECISION_CONFIRM, operator=OPERATOR,
        opportunity_mode=qr.OPPORTUNITY_CREATE_NEW, quote_number="CN01005",
        quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL,
    )
    (r,) = rc.reconcile_email_confirmations(review, ledger.states())
    assert (r.email_id, r.outcome, r.document_sha256) == (1, rc.RECONCILED, quote)
    assert r.email_decision["decision_id"] == entry["decision_id"]
    assert not doc_ledger.path.exists()  # reconciliation is computed, never written


# --- one email, several quotation documents -----------------------------------------------


def test_one_email_with_multiple_quote_documents_refuses_email_level_confirmation(world, tmp_path) -> None:
    a, b = _two_quote_email(world)
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)

    with pytest.raises(qr.ReviewRefused, match="2 quotation documents"):
        rc.record_email_decision(
            staging, ledger, review, 1, decision=qr.DECISION_CONFIRM, operator=OPERATOR,
            opportunity_mode=qr.OPPORTUNITY_CREATE_NEW, quote_number="CN01010",
            quote_number_basis=qr.BASIS_OPERATOR_ENTERED, reason="typed",
        )
    assert not ledger.path.exists()

    # A confirmation that predates the rule is kept as history and reconciled to nothing.
    historical = qr.build_decision(
        staging.item(1), decision=qr.DECISION_CONFIRM, operator=OPERATOR,
        opportunity_mode=qr.OPPORTUNITY_CREATE_NEW, quote_number="CN01010",
        quote_number_basis=qr.BASIS_OPERATOR_ENTERED, reason="typed",
    )
    ledger.append(historical)
    (r,) = rc.reconcile_email_confirmations(review, ledger.states())
    assert (r.outcome, r.document_sha256) == (rc.REFUSED_SEVERAL_QUOTE_DOCUMENTS, None)
    eff = rc.effective_document_states(review, doc_ledger, ledger.states())
    assert eff == {}  # neither document is confirmed by the email
    assert ledger.entries() == [historical]


def test_ambiguous_document_or_disagreeing_number_is_not_reconciled(world, tmp_path) -> None:
    lines = [ln for ln in _quote("1011-26", "Nadie") if not ln.startswith("At.")]
    world.email(1, [world.file("CN01011-sin cliente.pdf", lines)])
    world.email(2, [world.file("CN01012-Cliente Dos.pdf", _quote("1012-26", "Cliente Dos SpA"))])
    staging, review = _build(world)
    ledger, _ = _ledgers(tmp_path)

    code, _ = rc.email_confirmation_refusal(review, 1, "CN01011")
    assert code == rc.REFUSED_DOCUMENT_AMBIGUOUS
    code, message = rc.email_confirmation_refusal(review, 2, "CN01099")
    assert code == rc.REFUSED_NUMBER_DISAGREES and "1012-26" in message
    with pytest.raises(qr.ReviewRefused, match="does not print one unambiguous client"):
        rc.record_email_decision(
            staging, ledger, review, 1, decision=qr.DECISION_CONFIRM, operator=OPERATOR,
            opportunity_mode=qr.OPPORTUNITY_CREATE_NEW, quote_number="CN01011",
            quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL,
        )
    assert not ledger.path.exists()


# --- duplicate emails, one document --------------------------------------------------------


def test_duplicate_emails_pointing_to_the_same_sha_are_one_quote(world, tmp_path) -> None:
    quote, _ = _quote_with_duplicate(world)
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)

    (cand,) = review.candidates
    assert cand.sha256 == quote and cand.email_ids == (1, 2)
    _historical_email_confirm(staging, ledger, 1, "CN01005")
    _historical_email_confirm(staging, ledger, 2, "CN01005")

    recs = rc.reconcile_email_confirmations(review, ledger.states())
    assert [(r.email_id, r.outcome, r.document_sha256) for r in recs] == [
        (1, rc.RECONCILED, quote), (2, rc.RECONCILED, quote),
    ]
    eff = rc.effective_document_states(review, doc_ledger, ledger.states())
    assert list(eff) == [quote]  # one document, one confirmation
    assert [x["email_id"] for x in eff[quote].email_confirmations] == [1, 2]
    (plan,) = dr.opportunity_plans(review, doc_ledger, eff)
    assert [q.document_sha256 for q in plan.quotes] == [quote]  # never a second quote


def test_duplicate_emails_confirmed_against_different_opportunities_reconcile_to_nothing(world, tmp_path) -> None:
    quote, _ = _quote_with_duplicate(world)
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)
    _historical_email_confirm(staging, ledger, 1, "CN01005")
    _historical_email_confirm(staging, ledger, 2, "CN01005", opportunity_mode=qr.OPPORTUNITY_EXISTING,
                              opportunity_id=str(uuid.uuid4()))

    recs = rc.reconcile_email_confirmations(review, ledger.states())
    assert {r.outcome for r in recs} == {rc.REFUSED_DUPLICATES_DISAGREE}
    assert rc.effective_document_states(review, doc_ledger, ledger.states()) == {}


# --- the 706492 reconciliation ---------------------------------------------------------------


def test_email_level_confirmation_reconciles_to_one_canonical_document(world, tmp_path) -> None:
    quote, brochure = _quote_with_duplicate(world)
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)
    email = _historical_email_confirm(staging, ledger, 1, "CN01005")
    ledger.append(qr.build_decision(staging.item(2), decision=qr.DECISION_PENDING, operator=OPERATOR))

    eff = rc.effective_document_states(review, doc_ledger, ledger.states())
    assert list(eff) == [quote]  # the brochure is never reconciled
    st = eff[quote]
    assert (st.status, st.source) == (qr.STATUS_CONFIRMED, rc.SOURCE_EMAIL_RECONCILIATION)
    e = st.latest
    assert e["document_sha256"] == quote
    assert e["quote_number"] == "1005-26"  # the printed number, canonical
    assert e["quote_number_basis"] == rc.BASIS_EMAIL_RECONCILIATION
    assert e["applied"] is False and e["reconciled"] is True
    assert e["canonical_email_id"] == 1 and e["duplicate_email_ids"] == [2]

    item1, item2 = staging.item(1), staging.item(2)
    occ = {o["email_id"]: o for o in e["occurrences"]}
    for item in (item1, item2):
        o = occ[item.email_id]
        assert o["gmail_message_id"] == item.gmail_message_id
        assert o["rfc822_message_id"] == item.rfc822_message_id
        assert o["gmail_thread_id"] == item.gmail_thread_id
        assert o["source_attachment_id"] == next(d.source_attachment_id for d in item.documents if d.sha256 == quote)
    (src,) = e["source_email_decisions"]
    assert src["decision_id"] == email["decision_id"]
    assert (src["email_id"], src["gmail_message_id"], src["rfc822_message_id"], src["gmail_thread_id"],
            src["quote_number"]) == (1, item1.gmail_message_id, item1.rfc822_message_id, item1.gmail_thread_id, "CN01005")

    # Deterministic: the same ledgers always give the same planned opportunity.
    again = rc.effective_document_states(review, doc_ledger, ledger.states())[quote].latest
    assert again["opportunity"]["planned_opportunity_id"] == e["opportunity"]["planned_opportunity_id"]


def test_reconciled_confirmation_counts_for_document_rules(world, tmp_path) -> None:
    quote, _ = _quote_with_duplicate(world)
    # Another document (its own printed number, so the first stays unambiguous) that an
    # operator wants to record as 1005-26.
    other = world.file("CN01020-Cliente Ejemplo SpA.pdf", _quote("1020-26", "Cliente Ejemplo SpA"))
    world.email(3, [other])
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)
    _historical_email_confirm(staging, ledger, 1, "CN01005")
    eff = rc.effective_document_states(review, doc_ledger, ledger.states())
    assert eff[quote].source == rc.SOURCE_EMAIL_RECONCILIATION

    # The same printed number under another opportunity is refused, as for a document decision.
    with pytest.raises(qr.ReviewRefused, match="another opportunity"):
        dr.record_document_decision(
            review, doc_ledger, other[1], current=eff, decision=qr.DECISION_CONFIRM, operator=OPERATOR,
            opportunity_mode=qr.OPPORTUNITY_EXISTING, opportunity_id=str(uuid.uuid4()),
            quote_number="1005-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED, reason="resend",
        )
    # Joining the reconciled planned opportunity by typing its id is allowed.
    pid = eff[quote].latest["opportunity"]["planned_opportunity_id"]
    dr.record_document_decision(
        review, doc_ledger, other[1], current=eff, decision=qr.DECISION_CONFIRM, operator=OPERATOR,
        opportunity_mode=dr.OPPORTUNITY_PLANNED, opportunity_id=pid,
        quote_number="1005-26", quote_number_basis=qr.BASIS_OPERATOR_ENTERED, reason="resend of 1005-26",
    )


def test_document_decision_wins_and_never_rewrites_email_history(world, tmp_path) -> None:
    quote, _ = _quote_with_duplicate(world)
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)
    _historical_email_confirm(staging, ledger, 1, "CN01005")
    before = ledger.path.read_bytes()

    dr.record_document_decision(
        review, doc_ledger, quote, email_states=ledger.states(),
        current=rc.effective_document_states(review, doc_ledger, ledger.states()),
        decision=qr.DECISION_REJECT, operator=OPERATOR, reason="internal draft, never a quotation",
    )
    st = rc.effective_document_states(review, doc_ledger, ledger.states())[quote]
    assert (st.status, st.source) == (qr.STATUS_REJECTED, rc.SOURCE_DOCUMENT_DECISION)
    assert st.superseded_by_document_decision and [x["email_id"] for x in st.email_confirmations] == [1]
    assert ledger.path.read_bytes() == before  # the email decision is untouched
    assert ledger.states()[1].status == qr.STATUS_CONFIRMED


# --- the email queue's documentary status -------------------------------------------------


def _doc_status(review, doc_ledger, ledger, email_id):
    eff = rc.effective_document_states(review, doc_ledger, ledger.states())
    ds = rc.email_document_status(review, email_id, eff)
    return ds, rc.queue_bucket(ledger.states().get(email_id, qr.ItemState()), ds)


def test_an_email_whose_document_is_confirmed_is_not_pending(world, tmp_path) -> None:
    quote, _ = _quote_with_duplicate(world)
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)

    ds, bucket = _doc_status(review, doc_ledger, ledger, 2)
    assert (ds.status, bucket) == (rc.DOC_STATUS_PENDING, rc.QUEUE_PENDING)

    # Email 1 is confirmed at email level and reconciles; email 2 carries the same bytes and
    # has no decision of its own — it is settled by the document, not left pending.
    _historical_email_confirm(staging, ledger, 1, "CN01005")
    ds1, bucket1 = _doc_status(review, doc_ledger, ledger, 1)
    ds2, bucket2 = _doc_status(review, doc_ledger, ledger, 2)
    assert (ds1.status, ds1.confirmed, bucket1) == (rc.DOC_STATUS_CONFIRMED, (quote,), qr.STATUS_CONFIRMED)
    assert (ds2.status, ds2.confirmed, bucket2) == (rc.DOC_STATUS_CONFIRMED, (quote,), rc.QUEUE_SETTLED_BY_DOCUMENT)
    assert 2 not in ledger.states()  # the two states stay separate: nothing written for email 2


def test_an_email_is_settled_only_when_every_quote_document_is_decided(world, tmp_path) -> None:
    a, b = _two_quote_email(world)
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)

    dr.record_document_decision(
        review, doc_ledger, a, decision=qr.DECISION_CONFIRM, operator=OPERATOR,
        opportunity_mode=qr.OPPORTUNITY_CREATE_NEW, quote_number="1007-26",
        quote_number_basis=qr.BASIS_CONFIRMED_PROPOSAL,
    )
    ds, bucket = _doc_status(review, doc_ledger, ledger, 1)
    assert (ds.status, ds.confirmed, ds.pending, bucket) == (rc.DOC_STATUS_PARTIAL, (a,), (b,), rc.QUEUE_PENDING)

    dr.record_document_decision(
        review, doc_ledger, b, decision=qr.DECISION_REJECT, operator=OPERATOR, reason="internal draft",
    )
    ds, bucket = _doc_status(review, doc_ledger, ledger, 1)
    assert (ds.status, ds.rejected, bucket) == (rc.DOC_STATUS_CONFIRMED, (b,), rc.QUEUE_SETTLED_BY_DOCUMENT)


def test_an_email_without_a_quote_document_stays_pending(world, tmp_path) -> None:
    world.email(1, [world.file("Leaflet-Ejemplo.PDF", BROCHURE)])
    staging, review = _build(world)
    ledger, doc_ledger = _ledgers(tmp_path)
    ds, bucket = _doc_status(review, doc_ledger, ledger, 1)
    assert (ds.status, ds.settled, bucket) == (rc.DOC_STATUS_NONE, False, rc.QUEUE_PENDING)


# --- the chain stays visible ---------------------------------------------------------------


@pytest.fixture
def recon_server(world, tmp_path: Path):
    quote, brochure = _quote_with_duplicate(world)
    report, _ = world.audit()
    identity_dir = tmp_path / "identity"
    identity_dir.mkdir()
    (identity_dir / "quote_document_identity.json").write_text(json.dumps(report), encoding="utf-8")
    staging = qr.load_staging(world.staging_dir)
    ledger, doc_ledger = _ledgers(tmp_path)
    _historical_email_confirm(staging, ledger, 1, "CN01005")

    script = _load_script("quote_evidence_review_script_recon")
    httpd = ThreadingHTTPServer(("127.0.0.1", 0), None)
    port = httpd.server_address[1]
    httpd.RequestHandlerClass = script.make_handler(
        staging, ledger, OPERATOR, port, identity=script.load_identity(identity_dir),
        identity_dir=identity_dir, documents_root=world.docs_root, document_ledger=doc_ledger,
    )
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    yield port, quote, ledger, doc_ledger
    httpd.shutdown()


def test_chain_remains_visible_after_reconciliation(recon_server) -> None:
    port, quote, ledger, doc_ledger = recon_server

    # Document page: both emails, both chains, the email decision as history.
    status, html, _ = _req(port, "GET", f"/documento/{quote}", origin=None)
    assert status == 200
    for needle in ("/item/1", "/item/2", "/item/1/cadena", "/item/2/cadena", "conciliación",
                   "CN01005", "1005-26", "evidencia histórica"):
        assert needle in html, needle

    # Email page: where the confirmation went, and the chain.
    status, html, _ = _req(port, "GET", "/item/1", origin=None)
    assert status == 200
    assert f"/documento/{quote}" in html and "/item/1/cadena" in html
    assert "Conciliada con su documento canónico" in html
    status, html, _ = _req(port, "GET", "/item/2", origin=None)
    assert status == 200 and f"/documento/{quote}" in html  # the duplicate points at the same document

    # Opportunity / quote review: one quote, with every email and its chain.
    status, html, _ = _req(port, "GET", "/documentos", origin=None)
    assert status == 200
    assert html.count(f"/documento/{quote}'>CN01005-Cliente Ejemplo SpA.pdf") == 1
    assert "/item/1/cadena" in html and "/item/2/cadena" in html and "conciliada desde correo" in html

    # The chain itself, and a document decision that leaves the email ledger alone.
    status, html, _ = _req(port, "GET", "/item/1/cadena", origin=None)
    assert status == 200 and "/item/2" in html
    before = ledger.path.read_bytes()
    status, _, _ = _req(port, "POST", f"/documento/{quote}/decide", {
        "decision": qr.DECISION_CONFIRM, "opportunity_mode": qr.OPPORTUNITY_CREATE_NEW,
        "quote_number": "1005-26", "quote_number_basis": qr.BASIS_CONFIRMED_PROPOSAL,
    })
    assert status == 303
    assert ledger.path.read_bytes() == before
    status, html, _ = _req(port, "GET", f"/documento/{quote}", origin=None)
    assert "/item/1/cadena" in html and "/item/2/cadena" in html and "reemplazada" in html


# --- Drive evidence ------------------------------------------------------------------------


def _with_drive_id(world: World, email_id: int, sha: str, drive_id: str) -> None:
    for rec in world.records:
        if rec["payload"]["source_email_id"] == email_id:
            for d in rec["payload"]["documents"]:
                if d["sha256"] == sha:
                    d["drive_file_id"] = drive_id


def test_drive_evidence_matches_by_exact_id_and_local_hash(world) -> None:
    quote, _ = _quote_with_duplicate(world)
    _with_drive_id(world, 1, quote, DRIVE_ID)
    staging, review = _build(world)
    data = next(world.docs_dir.glob(f"{quote}.pdf")).read_bytes()

    meta = {"id": DRIVE_ID, "name": "CN01005-Cliente Ejemplo SpA.pdf", "mimeType": "application/pdf",
            "modifiedTime": "2026-03-18T18:00:00.000Z", "md5Checksum": "not-trusted"}
    good = de.drive_fetch_record(DRIVE_ID, meta, data, fetched_at=FETCHED_AT)
    assert good.sha256 == hashlib.sha256(data).hexdigest() == quote
    # Same name, another id: not the file the manifest names, so attached to nothing.
    lookalike = de.drive_fetch_record("9ZzZzZzZzZzZzZzZzZzZzZ", {**meta, "id": "9ZzZzZzZzZzZzZzZzZzZzZ"},
                                      data, fetched_at=FETCHED_AT)
    idx = de.build_drive_evidence(staging, review, {DRIVE_ID: good, lookalike.drive_file_id: lookalike})
    (ev,) = idx.for_document(quote)
    assert (ev.status, ev.drive_file_id, ev.manifest_occurrences[0][0]) == (de.DRIVE_HASH_MATCH, DRIVE_ID, 1)
    assert (ev.fetch.name, ev.fetch.mime_type, ev.fetch.modified_time) == (
        "CN01005-Cliente Ejemplo SpA.pdf", "application/pdf", "2026-03-18T18:00:00.000Z")
    assert idx.unreferenced_fetches == (lookalike,)

    changed = de.drive_fetch_record(DRIVE_ID, meta, data + b"\n", fetched_at=FETCHED_AT)
    (ev,) = de.build_drive_evidence(staging, review, {DRIVE_ID: changed}).for_document(quote)
    assert ev.status == de.DRIVE_HASH_MISMATCH and quote in ev.reason

    with pytest.raises(qr.StagingInconsistent, match="not the same file"):
        de.drive_fetch_record(DRIVE_ID, {**meta, "id": "1OtherOtherOtherOther"}, data, fetched_at=FETCHED_AT)


def test_drive_evidence_is_read_only(world, tmp_path) -> None:
    quote, _ = _quote_with_duplicate(world)
    _with_drive_id(world, 1, quote, DRIVE_ID)
    staging, review = _build(world)
    fetch_file = tmp_path / "drive" / "drive_fetch.json"
    fetch_file.parent.mkdir()
    data = next(world.docs_dir.glob(f"{quote}.pdf")).read_bytes()
    fetch_file.write_text(json.dumps([de.drive_fetch_record(
        DRIVE_ID, {"id": DRIVE_ID, "name": "x.pdf", "mimeType": "application/pdf", "modifiedTime": "t"},
        data, fetched_at=FETCHED_AT).as_dict()]), encoding="utf-8")
    before = _tree(tmp_path)

    idx = de.build_drive_evidence(staging, review, de.load_drive_fetches(fetch_file))
    assert idx.for_document(quote)[0].status == de.DRIVE_HASH_MATCH
    assert _tree(tmp_path) == before

    # The module has no network client and no write path.
    tree = ast.parse(_DRIVE_MODULE.read_text(encoding="utf-8"))
    imported = {a.name for n in ast.walk(tree) if isinstance(n, ast.Import) for a in n.names}
    imported |= {n.module or "" for n in ast.walk(tree) if isinstance(n, ast.ImportFrom)}
    assert not [m for m in imported if m.startswith(
        ("googleapiclient", "google", "requests", "httpx", "urllib", "subprocess", "sqlite3", "psycopg"))], imported
    calls = {n.func.attr for n in ast.walk(tree) if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute)}
    assert not calls & {"write", "write_text", "write_bytes", "unlink", "rename", "replace", "mkdir"}
    opens = [n for n in ast.walk(tree) if isinstance(n, ast.Call) and getattr(n.func, "attr", None) == "open"]
    assert opens and all(not n.args and all(k.arg == "encoding" for k in n.keywords) for n in opens)  # read mode only
    # The reconciliation module never appends to a ledger itself.
    recon = ast.parse(_RECONCILE_MODULE.read_text(encoding="utf-8"))
    ledger_writes = [n for n in ast.walk(recon) if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute)
                     and n.func.attr == "append" and "ledger" in ast.unparse(n.func.value)]
    assert ledger_writes == []


def test_failed_drive_access_changes_nothing_and_says_why(world, tmp_path) -> None:
    quote, _ = _quote_with_duplicate(world)
    _with_drive_id(world, 1, quote, DRIVE_ID)
    report, _ = world.audit()
    staging = qr.load_staging(world.staging_dir)
    ledger, doc_ledger = _ledgers(tmp_path)
    _historical_email_confirm(staging, ledger, 1, "CN01005")
    error = "HttpError 403: The user does not have sufficient permissions for this file."
    fetch_file = tmp_path / "drive" / "drive_fetch.json"
    fetch_file.parent.mkdir()
    fetch_file.write_text(json.dumps([de.drive_unavailable_record(DRIVE_ID, error, fetched_at=FETCHED_AT).as_dict()]),
                          encoding="utf-8")
    identity_dir = tmp_path / "identity"
    identity_dir.mkdir()
    (identity_dir / "quote_document_identity.json").write_text(json.dumps(report), encoding="utf-8")
    before = _tree(world.docs_root) | _tree(tmp_path / "review") | _bytes(doc_ledger.path, fetch_file)

    review = dr.build_document_review(staging, report)
    (ev,) = de.build_drive_evidence(staging, review, de.load_drive_fetches(fetch_file)).for_document(quote)
    assert (ev.status, ev.reason) == (de.DRIVE_UNAVAILABLE, error)
    # With no id in the manifest, the reason says so.
    (none,) = de.build_drive_evidence(staging, review, {}).for_document(quote)
    assert none.reason == f"Drive file {DRIVE_ID} is in the manifest but was not fetched"

    script = _load_script("quote_evidence_review_script_drive")
    httpd = ThreadingHTTPServer(("127.0.0.1", 0), None)
    port = httpd.server_address[1]
    httpd.RequestHandlerClass = script.make_handler(
        staging, ledger, OPERATOR, port, identity=script.load_identity(identity_dir), identity_dir=identity_dir,
        documents_root=world.docs_root, document_ledger=doc_ledger, drive_evidence_path=fetch_file,
    )
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    try:
        status, html, _ = _req(port, "GET", f"/documento/{quote}", origin=None)
        assert status == 200
        assert "Drive evidence unavailable" in html and "HttpError 403" in html and DRIVE_ID in html
        assert "/item/1/cadena" in html  # the email chain is still there
        assert _req(port, "POST", "/drive", {"x": "y"})[0] == 404  # no Drive write route exists
    finally:
        httpd.shutdown()
    after = _tree(world.docs_root) | _tree(tmp_path / "review") | _bytes(doc_ledger.path, fetch_file)
    assert after == before


def test_document_without_drive_id_reports_the_manifest_gap(world) -> None:
    quote, _ = _quote_with_duplicate(world)
    staging, review = _build(world)
    (ev,) = de.build_drive_evidence(staging, review, {}).for_document(quote)
    assert (ev.status, ev.drive_file_id, ev.reason) == (de.DRIVE_UNAVAILABLE, None, de.REASON_NO_DRIVE_ID)


def test_queue_shows_email_and_document_status_separately(recon_server) -> None:
    port, quote, ledger, doc_ledger = recon_server

    status, html, _ = _req(port, "GET", "/", origin=None)
    assert status == 200
    assert "Estado del correo" in html and "Estado documental" in html
    # Both emails show the document confirmation; only email 1 has an email decision.
    assert html.count("Cotización confirmada por documento</span>") == 2
    assert "Sin decisión de correo (resuelto por documento) (1)" in html
    assert "Pendiente (0)" in html

    status, html, _ = _req(port, "GET", "/?status=pending", origin=None)
    assert "/item/1'" not in html and "/item/2'" not in html
    status, html, _ = _req(port, "GET", "/?doc=confirmed_by_document", origin=None)
    assert "/item/1'" in html and "/item/2'" in html

    status, html, _ = _req(port, "GET", "/item/2", origin=None)
    assert "Sin decisión de correo (resuelto por documento)" in html
    assert "Cotización confirmada por documento" in html
    status, html, _ = _req(port, "GET", "/item/1/cadena", origin=None)
    assert html.count("Cotización confirmada por documento") == 2
