#!/usr/bin/env python3
"""Operational trust scorecard: cohort, readiness fields, taxonomy, freshness, provenance."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from origenlab_email_pipeline.config import load_settings
from origenlab_email_pipeline.hunt_csv_alignment import describe_hunt_misalignment
from origenlab_email_pipeline.operational_trust import (
    TrustCheck,
    any_critical_failed,
    check_cohort_partition,
    check_provenance_db_path,
    check_readiness_critical_fields,
    check_stale_client_pack,
    check_taxonomy_hunt,
    leads_active_paths,
    trust_summary,
)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--repo-root", type=Path, default=REPO)
    p.add_argument(
        "--db",
        type=Path,
        default=None,
        help="SQLite path (for provenance compare; default from settings)",
    )
    p.add_argument(
        "--max-pack-age-hours",
        type=float,
        default=168.0,
        help="Fail if client_pack summary generated_at_utc is older than this (default: 168h = 7d)",
    )
    p.add_argument(
        "--json-out",
        type=Path,
        default=None,
        help="Scorecard JSON (default: reports/out/active/operational_trust_scorecard.json)",
    )
    p.add_argument(
        "--md-out",
        type=Path,
        default=None,
        help="Scorecard Markdown (default: docs/generated/operational_trust_scorecard.md)",
    )
    return p


def check_hunt_merged_alignment(current: Path, merged: Path) -> list[TrustCheck]:
    if not current.is_file():
        return [
            TrustCheck(
                "hunt_current_file",
                False,
                True,
                f"Missing hunt cohort file: {current}",
            )
        ]
    if not merged.is_file():
        return [
            TrustCheck(
                "hunt_merged_file",
                False,
                True,
                f"Missing merged hunt file: {merged}",
            )
        ]
    try:
        msg = describe_hunt_misalignment(current, merged)
    except (OSError, ValueError) as e:
        return [
            TrustCheck(
                "hunt_merged_read",
                False,
                True,
                f"Could not compare hunt CSVs: {e}",
            )
        ]
    hint = (
        " Remediation: re-run merge from current (e.g. "
        "`uv run python scripts/leads/merge_contact_hunt_enrichment.py -b reports/out/active/leads_contact_hunt_current.csv "
        "-e <enrichment.csv> -o reports/out/active/leads_contact_hunt_current_merged.csv`) "
        "or align merged `id_lead` set to current before import."
    )
    return [
        TrustCheck(
            "hunt_merged_id_alignment",
            msg is None,
            True,
            "current and merged id_lead sets match"
            if msg is None
            else msg.split("\n", 1)[0] + hint,
            details={"full_message": msg} if msg else {},
        )
    ]


def write_scorecard_json(path: Path, checks: list[TrustCheck], summary: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "summary": summary,
        "checks": [c.to_dict() for c in checks],
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_scorecard_md(path: Path, checks: list[TrustCheck], summary: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Operational trust scorecard",
        "",
        f"- **Total checks:** {summary['total']}",
        f"- **Critical failed:** {summary['critical_failed']}",
        f"- **Non-critical failed:** {summary['noncritical_failed']}",
        "",
        "| Status | Critical | Check | Message |",
        "|--------|----------|-------|---------|",
    ]
    for c in checks:
        st = "pass" if c.ok else "**fail**"
        cr = "yes" if c.critical else "no"
        msg = c.message.replace("|", "\\|")
        lines.append(f"| {st} | {cr} | `{c.check_id}` | {msg} |")
    lines.append("")
    lines.append("_Generated by `scripts/qa/audit_operational_trust.py`._")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def run(args: argparse.Namespace) -> int:
    repo = args.repo_root.resolve()
    db = args.db
    if db is None:
        db = load_settings().resolved_sqlite_path()
    else:
        db = db.resolve()
    paths = leads_active_paths(repo)
    json_out = getattr(args, "json_out", None) or (
        repo / "reports" / "out" / "active" / "operational_trust_scorecard.json"
    )
    md_out = getattr(args, "md_out", None) or (
        repo / "docs" / "generated" / "operational_trust_scorecard.md"
    )

    checks: list[TrustCheck] = []
    checks.extend(
        check_cohort_partition(
            paths.hunt.resolve(),
            paths.ready.resolve(),
            paths.needs.resolve(),
            paths.not_ready.resolve(),
        )
    )
    checks.extend(
        check_readiness_critical_fields(
            paths.ready.resolve(),
            paths.needs.resolve(),
            paths.not_ready.resolve(),
        )
    )
    checks.extend(check_taxonomy_hunt(paths.hunt.resolve()))
    checks.append(
        check_stale_client_pack(
            paths.client_pack_summary.resolve(),
            max_age_hours=args.max_pack_age_hours,
        )
    )
    checks.append(
        check_provenance_db_path(
            resolved_db=db,
            audit_md_path=paths.contact_audit_md.resolve(),
        )
    )
    checks.extend(
        check_hunt_merged_alignment(
            paths.hunt.resolve(),
            paths.merged_hunt.resolve(),
        )
    )

    summary = trust_summary(checks)
    write_scorecard_json(json_out.resolve(), checks, summary)
    write_scorecard_md(md_out.resolve(), checks, summary)
    print(f"Wrote {json_out}")
    print(f"Wrote {md_out}")

    for c in checks:
        mark = "OK  " if c.ok else "FAIL"
        crit = " [critical]" if c.critical else ""
        print(f"{mark}{crit} {c.check_id}: {c.message}")

    return 1 if any_critical_failed(checks) else 0


def main() -> None:
    raise SystemExit(run(build_parser().parse_args()))


if __name__ == "__main__":
    main()
