#!/usr/bin/env python3
"""Add an "existing contacts in DB" check to a contact-hunt CSV.

This is conservative: it compares lead organizations (domain or normalized name)
against `organization_master.key_contacts` / `total_contacts`.

Important:
- This does not guess individual contacts.
- It only tells you whether OrigenLab already has contact emails for the same org.
"""

from __future__ import annotations

import argparse
import csv
import sys
import unicodedata
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from origenlab_email_pipeline.config import load_settings
from origenlab_email_pipeline.db import connect
from origenlab_email_pipeline.leads_schema import ensure_leads_tables


def _normalize_name(s: str | None) -> str:
    if not s:
        return ""
    x = s.strip().lower()
    # Remove accents/diacritics.
    x = "".join(c for c in unicodedata.normalize("NFKD", x) if not unicodedata.combining(c))
    # Strip common legal suffixes for conservative matching.
    for suffix in (" s.a.", " sa", " spa", " ltda", " s.a", " spa.", " ltda."):
        if x.endswith(suffix):
            x = x[: -len(suffix)].strip()
    # Keep only alnum + spaces.
    x = "".join(ch if (ch.isalnum() or ch.isspace()) else " " for ch in x)
    x = " ".join(x.split())
    return x


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Check whether lead organizations already have existing contacts in the email DB (organization_master/contact_master)."
    )
    ap.add_argument(
        "--input",
        "-i",
        type=Path,
        required=True,
        help="Input Spanish contact-hunt CSV (generated by export_contact_hunt_sheet.py or similar).",
    )
    ap.add_argument("--out", "-o", type=Path, required=True, help="Output CSV path.")
    ap.add_argument("--db", type=Path, default=None, help="SQLite path (default: from config).")
    ap.add_argument(
        "--exclude-has-contacts",
        action="store_true",
        help="If set, skip leads where DB already has key contacts for the matched org.",
    )
    args = ap.parse_args()

    settings = load_settings()
    db_path = args.db or settings.resolved_sqlite_path()

    conn = connect(db_path)
    ensure_leads_tables(conn)

    # Load organization_master for matching.
    # We prefer domain match; name match is accent-insensitive.
    org_rows = conn.execute(
        """
        SELECT domain, organization_name_guess, key_contacts, total_contacts
        FROM organization_master
        """
    ).fetchall()

    # Values:
    # (matched_domain, matched_org_name_guess, key_contacts, total_contacts)
    org_by_domain: dict[str, tuple[str | None, str | None, str | None, int]] = {}
    org_by_name: dict[str, tuple[str | None, str | None, str | None, int]] = {}
    for domain, name_guess, key_contacts, total_contacts in org_rows:
        dom = (domain or "").strip().lower()
        nk = _normalize_name(name_guess)
        # Stash domain first.
        if dom:
            org_by_domain.setdefault(
                dom,
                (domain, name_guess, key_contacts, int(total_contacts or 0)),
            )
        # Name fallback.
        if nk and nk not in org_by_name:
            org_by_name[nk] = (domain, name_guess, key_contacts, int(total_contacts or 0))

    # Read input sheet (already Spanish, has id_lead).
    with args.input.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        input_rows = list(reader)
        headers = reader.fieldnames or []

    if "id_lead" not in headers:
        raise SystemExit("Input CSV must include `id_lead` column.")

    lead_ids: list[int] = []
    for r in input_rows:
        try:
            lead_ids.append(int((r.get("id_lead") or "").strip()))
        except ValueError:
            pass
    if not lead_ids:
        raise SystemExit("No valid `id_lead` found in input CSV.")

    # Fetch lead_master fields needed for matching (domain + org_name).
    placeholders = ", ".join(["?"] * len(lead_ids))
    lm_rows = conn.execute(
        f"""
        SELECT id, org_name, domain
        FROM lead_master
        WHERE id IN ({placeholders})
        """,
        tuple(lead_ids),
    ).fetchall()
    conn.close()

    lead_by_id: dict[int, tuple[str | None, str | None]] = {
        int(i): (o, d) for (i, o, d) in lm_rows
    }

    # Output columns.
    extra_headers = [
        "tiene_contactos_en_db",
        "contactos_existentes_clave",
        "organizacion_match_db",
        "dominio_match_db",
        "total_contactos_db",
    ]
    out_headers = list(headers) + extra_headers

    out_rows: list[dict[str, str]] = []
    for r in input_rows:
        rid_raw = r.get("id_lead") or ""
        try:
            rid = int(rid_raw.strip())
        except ValueError:
            continue
        org_name, lead_domain = lead_by_id.get(rid, (None, None))

        dom = (lead_domain or "").strip().lower()
        lk = _normalize_name(org_name)

        if dom and dom in org_by_domain:
            match = org_by_domain[dom]
            match_domain, match_name, key_contacts, total_contacts = match
            match_org_name = match_name
        elif lk and lk in org_by_name:
            match_domain, match_name, key_contacts, total_contacts = org_by_name[lk]
            match_org_name = match_name
        else:
            match_domain, key_contacts, total_contacts = None, None, 0
            match_org_name = None

        has_contacts = 1 if (key_contacts and str(key_contacts).strip() and (total_contacts or 0) > 0) else 0

        if args.exclude_has_contacts and has_contacts == 1:
            continue

        row_out = dict(r)
        row_out["tiene_contactos_en_db"] = str(has_contacts)
        row_out["contactos_existentes_clave"] = key_contacts or ""
        row_out["organizacion_match_db"] = match_org_name or ""
        row_out["dominio_match_db"] = match_domain or ""
        row_out["total_contactos_db"] = str(total_contacts or 0)
        out_rows.append(row_out)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=out_headers)
        writer.writeheader()
        writer.writerows(out_rows)

    print(f"Wrote: {args.out} ({len(out_rows)} filas).")
    return 0


if __name__ == "__main__":
    sys.exit(main())

